### ISSUE TITLE
typo in installation instructions

### ISSUE THREAD

**Issue by alicef** [AutonomyLab/ardrone_autonomy#101]
There is a documentation problem
https://github.com/AutonomyLab/ardrone_autonomy#installation
it says: sudo apt-get install ros-hydro-ardrone_autonomy but that is WRONG
it should be:  sudo apt-get install ros-hydro-ardrone-autonomy with a "-" and not a "_"

**Comment by mani-monaj** [comment]
Thanks. I'll fix that.
