### ISSUE TITLE
Tag recognition doesn't work

### ISSUE THREAD

**Issue by lucsev** [AutonomyLab/ardrone_autonomy#102]
Hello everyone, 

I am trying to use the ardrone_autonomy package to track the orange-yellow-orange markers that my AR.Drone 1.0 comes with. I have received the /ardrone/navdata messages hoping that the tags would be identified. However, tag count is always 0 and no tags are perceived. My firmware version is 1.11.5 and I am using ROS Fuerte.

Apart from the markers issue, I am having the same problem with the camera toggle as this users:

https://github.com/AutonomyLab/ardrone_autonomy/issues/54

When I call the /ardrone/togglecam service, the image input actually changes to a zoomed area of the complete image that was previously seen. However, this images always come from the front camera.

Is there a solution yet?

Thanks in advance.

**Comment by mani-monaj** [comment]
I will investigate the issue.

**Comment by mani-monaj** [comment]
I ran the tag detection on both AR-Drone 1 (firmware 1.1.15) and  AR-Drone 2 (firmware 2.4.8) using driver version 1.3.3. 

The configuration was as follows ([From here](https://github.com/rabenimmermehr/ardrone_tutorials))

``` xml
<param name="detect_type" value="10" />
<param name="detections_select_h" value="32" /> 
<param name="detections_select_v_hsync" value="128" />
<param name="enemy_colors" value="2" />  <!-- Orange-Blue-Orange = 1,3 Orange-Yellow-Orange = 2 -->
<param name="enemy_without_shell" value="1" />  <!-- Detect the outdoor stickers, rather than the indoor hull -->
```

It worked perfectly (could detect Orange-Yellow-Orange stripes) on AR-Drone 2.0 but not at all on AR-Drone 1.0. I tried to play with parameters, but it led to nowhere. Please take a look at [this package](https://github.com/rabenimmermehr/ardrone_tutorials) for better visualization of tags and try to tweak some parameters yourself to see if you can make it work on AR-Drone 1.0.

**Comment by kbogert** [comment]
One problem I've noticed is that many people are using "rosrun ardrone_autonomy ardrone_driver -ip xxx.xxx.xxx.xxx" to run the driver.  The configuration for the tag detection is in the ardrone.launch file and should be run with:

roslaunch ardrone_autonomy ardrone.launch
