### ISSUE TITLE
Front Camera Grainy

### ISSUE THREAD

**Issue by prasadcheema** [AutonomyLab/ardrone_autonomy#103]
Hi,

When I open up rviz to look at the front camera images, I receive images which have lots of horizontal lines across it, is mildly grainy, and the camera seems to be seeing 'double'. Overall it is not very good image quality and so it cannot be worked with. I was wondering if someone here had a similar issue/has fixed it before, or perhaps I'm doing something silly.

Current Set Up: Recently bought ARDrone 2.0 (one month ago), ROS Hydro, Ubuntu 12.04.

**Comment by mani-monaj** [comment]
How does the camera feed look like in the iPhone/Android app?

**Comment by prasadcheema** [comment]
The camera feed in the iPhone is fine, as is the camera feed using the example compiled code in the SDK 2.0.1 for the drone. It's just when I try to get the feed through ROS

**Comment by mani-monaj** [comment]
Have you tried visualizing the video stream using `image_view` or `rqt_image_view`?

**Comment by mani-monaj** [comment]
One more question. Have you compiled the driver from source or are you using the binary from `apt-get`?

**Comment by prasadcheema** [comment]
My apologies I cannot fully remember how I compiled, as it was done quite a while ago. Knowing me, it probably would've been through the simplest method , so possibly by using apt-get??? Should I have not done it through this way?

**Comment by mani-monaj** [comment]
That's weird.
1. Have you tried visualizing the video stream using image_view or rqt_image_view?
2. Can you try to compile from source to see if the problem still happens?

**Comment by prasadcheema** [comment]
Ok thanks for your help. I'll try and implement your solution over the coming week and I will get back to you on the how things turn out. :)

**Comment by prasadcheema** [comment]
Hi Monaj, thanks for your suggestions. I've tried them all, and still have grainy images/images with horizontal lines across them. I have attached some images for you to look through:

![image_raw_comparison](https://cloud.githubusercontent.com/assets/7688512/3438712/c76cf6d8-00cf-11e4-8f03-913b9ba97b70.png)
![bad_image](https://cloud.githubusercontent.com/assets/7688512/3438713/caeef608-00cf-11e4-9fb2-db7c1b27623d.png)

The images show the quality coming out of rviz/rqt_image_view and image_view command. Moreover we have no access to the bottom camera. Is this normal, or is there some known connection issue with the ardrone bottom camera.

**Comment by prasadcheema** [comment]
I can select the bottom camera feed through typing in the command "rosservice call /ardrone/togglecam", so that issue seems to be solved. However the bad image streams for the top (and now bottom) cameras still persist. Can this issue be solved through the typical 'camera calibration' solution. Moreover, could you provide a possible reason as to why the stream is fine through mobile devices/SDK but not through ROS implementation of the SDK. I am very new to this topic and would appreciate your input. It will undoubtedly increase my understanding of the subject area.

**Comment by prasadcheema** [comment]
Just to resolve this issue, I have found and fixed the problem. It turned out that the firmware with the newer 2.0 Parrots cause this problem. I downgraded the firmware, and it's perfect now.

**Comment by mani-monaj** [comment]
@pche8701 Thanks for sharing that. Glad that you found out the root cause. Could you please indicated the problematic and working firmware versions?

**Comment by prasadcheema** [comment]
Unfortunately I cannot say what firmware we downgraded from (we accidentally deleted the file that would tell us :S). But we downgraded to 2.1.16, by following these following steps:

http://forum.parrot.com/ardrone/en/viewtopic.php?id=4936

All I can say about our ardrone's original firmware was that it was the newest version, since it was bought a month or two ago.
