### ISSUE TITLE
Binary installation

### ISSUE THREAD

**Issue by gariepyalex** [AutonomyLab/ardrone_autonomy#104]
Hi,
I am on a fresh installation of Ubuntu 13.04, using ros hydro. I followed the official instructions to install ros. I added : 

```
sudo sh -c 'echo "deb http://packages.ros.org/ros/ubuntu raring main" > /etc/apt/sources.list.d/ros-latest.list'
```

as instructed. I also updated apt properly ( `sudo apt-get update` ).

However, when I try to install with `apt-get install ros-hydro-ardrone_autonomy`, it cannot find the package. I get : 

```
E: Unable to locate package ros-hydro-ardrone_autonomy

```

I installed it last week and it just worked. Any ideas?

**Comment by mani-monaj** [comment]
You are right. The binary build on the buildfarm is broken at the moment. I am investigating the problem. Thank you very much for the report.

**Comment by mani-monaj** [comment]
Fixed in 1.3.4

**Comment by gariepyalex** [comment]
I still can't find it via apt-get.

**Comment by mani-monaj** [comment]
@gariepyalex Unfortunately the broken build on the buildfarm caused the package to be removed from ros  repositories. The new version is [on its way](http://packages.ros.org/ros-shadow-fixed/ubuntu/pool/main/r/ros-hydro-ardrone-autonomy/) to be pushed back. It usually takes some time between one week to two weeks. I am sorry for the inconvenience. In the meantime:
1. You can build the 1.3.4 from source. or 
2. Get the `.deb` file for your ubuntu version [from here](http://packages.ros.org/ros-shadow-fixed/ubuntu/pool/main/r/ros-hydro-ardrone-autonomy/). You can install that with `sudo dpkg -i xxx.deb`.

**Comment by mani-monaj** [comment]
@gariepyalex The binary for hydro should now be accessible via apt-get.

**Comment by gariepyalex** [comment]
Thank you!

**Comment by fig0451** [comment]
I've done everything the original poster did, and my ubuntu 12.04 is unable to find the package.

I have ROS installed, in case that is somehow required for finding the package.

**Comment by mani-monaj** [comment]
Please do a `sudo apt-get update` first before trying to install it.

**Comment by fig0451** [comment]
I did, but it did not make the apt-get for the binary work. Either way, I downloaded it and compiled it myself, so, problem solved! Thanks for your quick response :D

EDIT: The problem was that you have the package listed with a _ instead of a -
