### ISSUE TITLE
ardrone_autonomy segmentation fault

### ISSUE THREAD

**Issue by hsoltani** [AutonomyLab/ardrone_autonomy#105]
I want to run AR.Drone's driver by ardrone_autonomy package.I'm working on ROS hydro and Ubuntu 12.10. I get Segmentation fault (core dumped) error for following command:

rosrun ardrone_autonomy ardrone_driver

How can I fix this problem?

**Comment by mani-monaj** [comment]
Could you please provide the full console output? I am also interested to know if you compiled the driver from source or you are using the pre-build binary.

**Comment by hsoltani** [comment]
I compiled the driver from source with catkin workspace. I just get following message in terminal:
Segmentation fault (core dumped)

**Comment by mani-monaj** [comment]
Have you tried running the driver on another machine?

**Comment by mani-monaj** [comment]
I will close this due to inactivity. If you still have the problem, please update the issue with new details and re-open it.
