### ISSUE TITLE
Where does the return value from for MD5Sum Navdata.h?

### ISSUE THREAD

**Issue by jw-dong** [AutonomyLab/ardrone_autonomy#107]
When I was launch my python node for the AR.Drone, there was an error message of return value mismatching for the MD5Sum of Navdata.h. 

I matched the values so it works now. I am just wondering where does this value from and what does it actually mean. It looks pretty random to me. 

template<class ContainerAllocator>
struct MD5Sum< ::ardrone_autonomy::Navdata_<ContainerAllocator> >
{
  static const char\* value()
  {
    return "e1169f766234363125ac62c9a3f87eeb"; 
  }

  static const char\* value(const ::ardrone_autonomy::Navdata_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe1169f7662343631ULL;
  static const uint64_t static_value2 = 0x25ac62c9a3f87eebULL;
};

**Comment by mani-monaj** [comment]
This is from [ROS Troubleshooting](http://wiki.ros.org/ROS/Troubleshooting#Network_Configuration):

> md5sum mismatch
> This is either two different versions of a message at either end or actually different messages.
> - Make sure that all directories are up to date and have been rebuilt by doing a rosmake in any package you are launching
>   Note: If you are running on multiple machines they must all be consistent.
> - Make sure that the sender and receiver are expecting the same message
> - If you're playing out of a log file the contents may be out of date see rosrecord
