### ISSUE TITLE
Front camera

### ISSUE THREAD

**Issue by hsoltani** [AutonomyLab/ardrone_autonomy#108]
Hi
I took out the front camera of AR.Drone and mounted on the bottom of the drone looking downwards. Should I change anything on ardrone_autonomy package (such as rotation matrix,...) for this situation?

**Comment by mani-monaj** [comment]
Yes, you need to change the `tf` transformation between `base_link` and `front_camera`. I suggest that you  change [this line](https://github.com/AutonomyLab/ardrone_autonomy/blob/hydro-devel/src/ardrone_driver.cpp#L82) of the file `src/ardrone_driver.cpp`. 

From: 

``` c
tf::createQuaternionFromRPY(-90.0 * _DEG2RAD, 0.0, -90.0 * _DEG2RAD),
```

To something like this:

``` c
 tf::createQuaternionFromRPY(-90.0 * _DEG2RAD, 0.0, -90.0 * _DEG2RAD) * tf::createQuaternionFromRPY(frontCamRotation * _DEG2RAD, 0.0, 0.0),
```

Assuming that you only pitched the camera downwards. If you made other rotations, you need to change the second term respectively. There is a sample implementation of this idea in `autolab` branch (`src/ardrone_driver.cpp`). The code is outdated though.
