### ISSUE TITLE
rosmake ardrone_autonomy permission issues

### ISSUE THREAD

**Issue by sidenoteemail** [AutonomyLab/ardrone_autonomy#11]
I apologize if I am posting this issue in the wrong area.  When I enter:

$ rosmake ardone_autonomy

I get the following message: 

mkdir: cannot create directory 'build': Permission denied

I have tried the follow to fix this:
$ sudo -i
$./build_sdk 

which executes, but when I go to rosmake ardone_autonomy I still get the same error.  Is there something simple I overlooked in the tutorial?  I am using the VirtualBox virtual image with Ubuntu 12.04.1 LTS and ROS Fuerte pre-installed.  If this is the incorrect location for this issue, could anyone point me to the correct forum.  Thank you

**Comment by mani-monaj** [comment]
This is more likely a permission issue for the `ardrone_autonomy` folder, make sure the current user has `rwx` permissions for this folder. Please also make sure that you put the driver somewhere other than `/opt/ros/`. 

These two links will probably help:

http://www.ros.org/wiki/ROS/Tutorials/InstallingandConfiguringROSEnvironment
http://answers.ros.org/question/9350/sudo-rosmake-permission-denied-problem/

**Comment by sidenoteemail** [comment]
Thanks for leading me in the right direction.  All permission issues have been resolved.

**Comment by mani-monaj** [comment]
Glad to hear that :)
