### ISSUE TITLE
Absolute Yaw and Altitude

### ISSUE THREAD

**Issue by ghost** [AutonomyLab/ardrone_autonomy#111]
Hello. This might be a layman's questions, but I am having some trouble accessing the "magnetic_degree" value from navdata_gps, which I assume is the magnetic yaw orientation of the drone (compass). It just returns 0.0, whether the drone is flying or not.  Could someone point me to a possible solution, or tell me if there is another way of obtaining absolute yaw orientation? Everything works fine when I use the FreeFlight app for absolute control.

Also, the elevation values are erratic, changing randomly whether the drone is moving or not (latitude and longitude values are ok) and far from the elevation values I get from the FreeFlight app (which are pretty good).  Any tips to solve that as well?

Thanks.  

PS: My firmware is 2.4.8, with all available upgrades.

**Comment by mani-monaj** [comment]
@vitorguizilini Could you please provide a step-by-step procedure so I can reproduce the errors?

**Comment by mani-monaj** [comment]
Are you using the code from the `gps` branch?

**Comment by ghost** [comment]
It is not an error, exactly, it is more that I don't know how to access compass and GPS altitude information. Which topics, and which fields, should I look for?  My goal here is to localize the drone in a 3D environment, and I need this information for autonomous navigation.

**Comment by ghost** [comment]
And yes, I am using the code from the GPS branch. I have access to latitude and longitude, and they work fine, however the altitude field returns seemingly nonsensical numbers, and I don't know how to retrieve compass information (absolute yaw).

**Comment by ghost** [comment]
Hi, I am just wondering if anyone has some advice for me, I really would like to get this working as quickly as possible.

**Comment by mani-monaj** [comment]
I would suggest that you enable all GPS navdata topcis and log all of them during a flight to see if any of them will give you the data you want. 

The compass reading (both raw and filtered) is accessible through non-GPS navdata topics.

**Comment by ghost** [comment]
Could you point me to the compass reading? I have searched all nodes and couldn't find any absolute yaw information, that I think should be the one given by the magnetometer. There are raw x,y and z magnetometer readings, but no specific bearing information.

Thanks.

**Comment by ghost** [comment]
Hi. I'm just bumping this topic because I still haven't found the compass reading in any of the topics published by ardrone_autonomy. I have access to the raw magnetometer data, however there should be a filtered absolute yaw reading, right?

Thanks.

**Comment by mani-monaj** [comment]
Unfortunately I don't have access to an AR-Drone at least for a month. Have you tried enabling [all optional messages](https://github.com/AutonomyLab/ardrone_autonomy#selective-navdata-advanced-new)?
