### ISSUE TITLE
Cannot Connect to Drone

### ISSUE THREAD

**Issue by fig0451** [AutonomyLab/ardrone_autonomy#114]
I get the following when I run rosrun ardrone_autonomy ardrone_driver

[ERROR] [1404269560.959048312]: [registerPublisher] Failed to contact master at [localhost:11311].  Retrying...

And nothing ever happens. I am connected to the drone, I can telnet into it at 192.168.1.1 no problem. It is not paired.

EDIT: Reading a bit more, I found a similar issue suggesting I run this:

roslaunch ardrone_autonomy ardrone.launch

This results in: 

[ardrone.launch] is neither a launch file in package [ardrone_autonomy] nor is [ardrone_autonomy] a launch file name

I guess I'll try reinstalling hydro?

EDIT2:

Reinstalled everything, same issues still present.

**Comment by fig0451** [comment]
Tried using groovy, same error. Can't connect.

**Comment by kbogert** [comment]
This sounds more like a ROS issue than ardrone_autonomy.  If roslaunch isn't working for you maybe your .bashrc isn't setup correctly?  How did you install ardrone_autonomy?

Can you post the output of:
    env | grep ROS
?

**Comment by kbogert** [comment]
Hmm, I just reproduced the roslaunch error with the binary ardrone_autonomy install, looks like the build missed the file.

Try using the rosrun method, but before your run it run "roscore" in a separate window.

**Comment by fig0451** [comment]
Here is env grep output:

``` bash
thursday@daedalus:~$ env | grep ROS
ROS_ROOT=/opt/ros/hydro/share/ros
ROS_PACKAGE_PATH=/opt/ros/hydro/share:/opt/ros/hydro/stacks
ROS_MASTER_URI=http://localhost:11311
ROSLISP_PACKAGE_DIRECTORIES=
ROS_DISTRO=hydro
ROS_ETC_DIR=/opt/ros/hydro/etc/ros
```

Also: Holy crap, that worked. Thank god. So is this a thing that needs to be fixed in the build/distro, or is there something I can do?

Thanks a ton for your help with this :D

Also Also: How to view a live stream of its input sensors that output numbers (magnetometer, accelerometer, etc)?

**Comment by mani-monaj** [comment]
@kbogert @fig0451 Thanks for getting to the bottom of this. I marked this issue as a bug and will fix it in the next release.
