### ISSUE TITLE
Timeout when reading navdatas

### ISSUE THREAD

**Issue by fig0451** [AutonomyLab/ardrone_autonomy#118]
Hi guys, got a new problem.

I open one terminal, run 'roscore' to initialize ros and get it running.
Open terminal two, run 'rosrun ardrone_autonomy ardrone_driver' to get the module running.
Open terminal three in examples, and try to do hover.js by running 'node hover.js'.

My console gets spammed with:

Timeout when reading navdatas - resending a navdata request on port 5554
Reconnecting ... OK
Reconnecting ... OK
Reconnecting ... OK
Timeout when reading navdatas - resending a navdata request on port 5554
Reconnecting ... OK
Reconnecting ... OK
Reconnecting ... OK

Any ideas why this is happening?

**Comment by tomas-c** [comment]
Having the same problem with two 2.0 quadcopters. Even when 1m away and not flying, navdata publish rates sometimes (for 5s every couple of minutes) slow down from 200Hz to 4-10Hz and then quadcopter reconnects. Definitely not WiFi interference as it happens even in an RF screen room.

**Comment by tomas-c** [comment]
Turns out my problem was the NetworkManager scanning for WiFi networks every few minutes. This caused delays in communication and in turn ardrone com watchdog timeouts. 

How often do you get those "Reconnecting ... OK" messages?

**Comment by fig0451** [comment]
Once the connection opens up it just spams it multiple times a second

**Comment by mani-monaj** [comment]
It is very likely a network/wifi issue. Any more investigations?

**Comment by safrimus** [comment]
I'm having the same issue as well, this is printed out on my console:

Reconnecting ... OK
Reconnecting ... OK
Sending default CAT_APPLI settings
Sending default CAT_USER settings
Sending default CAT_SESSION settings
[ INFO] [1422156308.410831027]: Successfully connected to 'My ARDrone' (AR-Drone 2.0 - Firmware: 2.4.8) - Battery(%): 0
[ INFO] [1422156308.420409877]: Navdata Publish Settings:
[ INFO] [1422156308.429347736]:     Legacy Navdata Mode: On
[ INFO] [1422156308.438117598]:     ROS Loop Rate: 50 Hz
[ INFO] [1422156308.444159503]:     Realtime Navdata Publish: Off
[ INFO] [1422156308.452091378]:     Realtime Video Publish: Off
[ INFO] [1422156308.460161251]:     Drone Navdata Send Speed: 200Hz (navdata_demo=0)
Reconnecting ... OK
Reconnecting ... OK
Reconnecting ... OK
....
Timeout when reading navdatas - resending a navdata request on port 5554
Reconnecting ... OK
...

I'm running this on a Raspberry Pi with ROS-groovy. Any suggestions?

**Comment by karim-nemra** [comment]
Hello I wanna use the new Parrot Bebop with ardrone_autonomy using PC with Linux 12.04 ans ROS hydro, I get the following message:
nemra@nemra-Z68X-UD4-B3:~/catkin_wsa$ rosrun /home/nemra/catkin_wsa/devel/lib/ardrone_autonomy ardrone_driver
[rospack] Error: stack/package /home/nemra/catkin_wsa/devel/lib/ardrone_autonomy not found
Wait authentification
Wait authentification
Wait authentification
===================+> nemra 192.168.1.1
[ INFO] [1423827846.447910671]: Root Frame is: 0
[ INFO] [1423827846.448939189]: No values found for `~cov/imu_la` in parameters, set all to zero.
[ INFO] [1423827846.449874967]: No values found for `~cov/imu_av` in parameters, set all to zero.
[ INFO] [1423827846.450714696]: No values found for `~cov/imu_or` in parameters, set all to zero.
Something must be really wrong with the SDK!Deleting Profile -cea48d22
Deleting Application -e182b69b
Input device Teleop added
Starting thread video_stage
Starting thread update_ros
Thread `update_ros` started 
 Set IP_TOS ok
Starting thread navdata_update

video stage thread initialisation

Starting thread ardrone_control
Thread navdata_update in progress...
Video multisocket : init 2 sockets
Video multisocket : connecting socket 0 on port 5555 UDP
Start thread thread_academy_download 
Academy download stage resumed
Video multisocket : connecting socket 1 on port 5555 TCP
PA : MEMORY SPACE ALLOWED : 40 MB
Start thread thread_academy
Start thread thread_academy_upload
Timeout when reading navdatas - resending a navdata request on port 5554
Timeout when reading navdatas - resending a navdata request on port 5554
Timeout when reading navdatas - resending a navdata request on port 5554
- Connection failed
  Academy download stage paused
  FTOSFC: No route to host
  Timeout when reading navdatas - resending a navdata request on port 5554
  Timeout when reading navdatas - resending a navdata request on port 5554
  [ INFO] [1423827851.488410487]:   SEND: CAT_APPLI/navdata_options = 268435456.000000 (DEFAULT = 65537.000000)
  Segmentation fault (core dumped)

Pleas any one can help me

**Comment by ganeshrk95** [comment]
Guys ! Any update on this issue? Facing the same problem on AR Drone 2.0 Power edition running 2.4.8 firmware.

-Ganesh

**Comment by tomas-c** [comment]
For me it was NetworkManager automatically scanning for WiFI networks every few minutes. Try setting up the connection using wpa_supplicant.
