### ISSUE TITLE
Reference frame confusion

### ISSUE THREAD

**Issue by davide-tateo90** [AutonomyLab/ardrone_autonomy#119]
EDIT: useless, I'm sorry :(

**Comment by davide-tateo90** [comment]
ok, it was a build issue, Im sorry...

**Comment by mani-monaj** [comment]
@boris-il-forte thanks for the report. 

Just to confirm:  #113 fixes the compatibility with ROS convention. right?

**Comment by davide-tateo90** [comment]
Yes now is consistent with Ros, I'm sorry, but I had problems with wstool, I should have check first that...

**Comment by mani-monaj** [comment]
@boris-il-forte Thank you. Could you please create one of those rviz screenshots (as in the original post of yours) so I can add that to wiki as a reference?

**Comment by davide-tateo90** [comment]
yes, of course. I will send you tomorrow some screenshots of the IMU and the tf frames.

**Comment by mani-monaj** [comment]
Thank you.

**Comment by davide-tateo90** [comment]
![tf3](https://cloud.githubusercontent.com/assets/1477896/3902400/6dba7b8c-22bd-11e4-80c0-8e7f50ab5722.png)
![imu](https://cloud.githubusercontent.com/assets/1477896/3902401/6dcf0214-22bd-11e4-898b-c4ad7c383fe8.png)
![tf1](https://cloud.githubusercontent.com/assets/1477896/3902402/6dd97ff0-22bd-11e4-974c-952ebbb97d3f.png)
![tf2](https://cloud.githubusercontent.com/assets/1477896/3902403/6de4eb1a-22bd-11e4-8adc-9b6589101c66.png)

**Comment by davide-tateo90** [comment]
![tf4](https://cloud.githubusercontent.com/assets/1477896/3902443/f322e0c0-22bd-11e4-845d-2bea1b9ae31c.png)

**Comment by mani-monaj** [comment]
@boris-il-forte Thank you. I will move these to wiki.
