### ISSUE TITLE
ARDrone SDK repository URI

### ISSUE THREAD

**Issue by kpykc** [AutonomyLab/ardrone_autonomy#122]
Hello,

I mentioned that SDK is now included as external project. 

```
include(ExternalProject)
ExternalProject_Add(ardronelib
    GIT_REPOSITORY git://github.com/AutonomyLab/ardronelib.git
    GIT_TAG bdacd1cbd3fbc54263d29e6e2067265e5941d10e
```

I believe this is right choice, however I would like to ask maintainers to change URI to `https`:

```
    GIT_REPOSITORY https://github.com/AutonomyLab/ardronelib.git
```

The reason for this is that `git` protocol is often shaped by firewall, as in my university for example (don't ask why), while `https` is usually passing. As a result, build will not be possible for  some `ardrone_autonomy`  package users without modification of `CMakeLists.txt`.

**Comment by mani-monaj** [comment]
Thank you for your suggestion. I've had some issues with the HTTPS protocol and SSL certificates on ROS buildfarm, that's why git protocol is being used.
