### ISSUE TITLE
Process has died

### ISSUE THREAD

**Issue by sbraune** [AutonomyLab/ardrone_autonomy#125]
So I can get one ARDrone to work with ROS but with lack of documentation on how to get two working, I am stuck. Here is my All.launch file

```
<group ns="ardrone1">
     <node name="ardrone_driver" pkg="ardrone_autonomy" type="ardrone_driver" args="-ip 192.168.12.10" />

</group>

<group ns="ardrone2">
 <node name="ardrone_driver" pkg="ardrone_autonomy" type="ardrone_driver" args="-ip 192.168.12.11" />
```

 </group>

After running the program, either the first one or the second one will give me this message. 

ardrone2/ardrone_driver1-6] process has died [pid 24117, exit code -11, cmd /home/tamucc/fuerte_workspace/sandbox/ardrone_autonomy/bin/ardrone_driver -ip 192.168.12.11 __name:=ardrone_driver1

Any help on how to resolve this issue will be grateful. I am using ROS Fuerte

**Comment by mani-monaj** [comment]
ROS Fuerte is End-Of-Lifed and is not supported anymore. The plugin code in Fuerte branch is also outdated. Please consider upgrading at least to _Hydro_. For running multiple instances, please check issue #56.

**Comment by sbraune** [comment]
Thanks for the reply, though you should make that clear on the branch readme that it is no longer being supported.

**Comment by mani-monaj** [comment]
You are right. I will update the branch READMEs.

**Comment by sbraune** [comment]
Thanks for the help. I am only using Fuerte because that is what my lab was using when I joined the project. Hopefully the change to Hydro will be pretty transparent and easy. Thanks again for your contribution to the world of UAVs.

**Comment by mani-monaj** [comment]
IMO It's even easier to work with this driver on _Hydro_ since you can install the binaries via `apt-get`. good luck flying robots :)
