### ISSUE TITLE
complie HEVC on ARM

### ISSUE THREAD

**Issue by darkmiss** [AutonomyLab/ardrone_autonomy#127]
I was trying to build HEVC on ARM,
I download the file in "https://github.com/OpenHEVC/openHEVC"
I tried the following
1. mkdir build
2. cd build
3. cmake -DCMAKE_BUILD_TYPE=RELEASE ..
4. make

/usr/bin/cc   -DUSE_SDL -O3 -DNDEBUG    CMakeFiles/hevc.dir/main_hm/getopt.c.o Cl,-Bstatic -lSDLmain -Wl,-Bdynamic -lSDL -lpthread

/usr/bin/ld.bfd.real: libLibOpenHevcWrapper.a(utils.c.o): undefined reference to
//lib/arm-linux-gnueabihf/libm.so.6: error adding symbols: DSO missing from comm
collect2: error: ld returned 1 exit status

I google for the error.
Lots of solutions are "add -ldl in makefile"
I tried to add it in the Cmakelist.txt ,but i failed

**Comment by mani-monaj** [comment]
This is not openHVEC's repo.
