### ISSUE TITLE
question: New AR.Drone 2.0 Elite compatibility 

### ISSUE THREAD

**Issue by alvaro893** [AutonomyLab/ardrone_autonomy#131]
Hi, I am very interest to start learning about autonomous drones, in the README section there is no mention the new ar.drone elite (it is the only one I saw on stores). Is it compatible with this libraries?

Thanks!

BR, Álvaro

**Comment by mani-monaj** [comment]
The driver should work fine with AR-Drone 2.0 elite edition.
