### ISSUE TITLE
Compilation error for HM 11.0 or 10.0 on UNIX

### ISSUE THREAD

**Issue by achraf-io** [AutonomyLab/ardrone_autonomy#138]
Hi everybody,
I upload HM to encode videos, but when I build on UNIX system I have this result:
$ make
make -C lib/TLibVideoIO         MM32=0
make[1] : on entre dans le répertoire « /home/root/HM-11.0/build/linux/lib/TLibVideoIO »
g++ -c -MMD -MF ./objects/TVideoIOYuv.d.d -MT ./objects/TVideoIOYuv.d.o -fPIC -DMSYS_LINUX -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64 -DMSYS_UNIX_LARGEFILE -I/home/root/HM-11.0/build/linux/lib/TLibVideoIO/../../../../source/Lib -I../../../../source/Lib/TLibVideoIO -Wall -Wshadow -Wno-sign-compare -Werror -g  -D_DEBUG -o objects/TVideoIOYuv.d.o /home/root/HM-11.0/build/linux/lib/TLibVideoIO/../../../../source/Lib/TLibVideoIO/TVideoIOYuv.cpp
/home/root/HM-11.0/build/linux/lib/TLibVideoIO/../../../../source/Lib/TLibVideoIO/TVideoIOYuv.cpp:1:0: erreur: -fPIC ignored for target (all code is position independent) [-Werror]
 /\* The copyright in this software is being made available under the BSD
 ^
cc1plus: all warnings being treated as errors
../../common/makefile.base:217 : la recette pour la cible « objects/TVideoIOYuv.d.o » a échouée
make[1]: **\* [objects/TVideoIOYuv.d.o] Erreur 1
make[1] : on quitte le répertoire « /home/root/HM-11.0/build/linux/lib/TLibVideoIO »
makefile:7 : la recette pour la cible « all » a échouée
make: **\* [all] Erreur 2
So if someone know how to solve this that's gonna be awesome , thanks to all

**Comment by mani-monaj** [comment]
Is it related to `ardrone_autonomy` or `ardronelib`? If yes, please re-open the ticket with more information.
