### ISSUE TITLE
navdata::tags_distance is float32[] but navdata_vision_detect::dist is uint32[]

### ISSUE THREAD

**Issue by Napoleon-BlownApart** [AutonomyLab/ardrone_autonomy#151]
In Navdata.msg, tags_distance is defined as float32[] but in  navdata_vision_detect dist is defined as uint32[].

Navdata is a legacy message, while navdata_vision_detect is a new message.

I believe they are the same information, so which is correct?

**Comment by mani-monaj** [comment]
According to [this](https://github.com/AutonomyLab/ardronelib/blob/2f987029c55531e4c0119c3600f9c57f935851ed/ARDroneLib/Soft/Lib/ardrone_tool/Navdata/ardrone_navdata_file.c#L558), `uint32` is the correct type.
