### ISSUE TITLE
Bug in odometry/tf position fixed: z-coordinate was only integer values

### ISSUE THREAD

**Issue by alexjung** [AutonomyLab/ardrone_autonomy#155]
I recorded some data flying an AR.Drone 2.0 and was wondering why the z-coordinate of odometry and tf was only jumping between 0, 1, 2 and so on.
I checked ARDroneDriver::PublishOdometry in ardrone_driver.cpp and fixed line 702 from
odo_msg.pose.pose.position.z = navdata_raw.navdata_demo.altitude / 1000; 
to
odo_msg.pose.pose.position.z = navdata_raw.navdata_demo.altitude / 1000.0;

Now I receive continuous values on odometry/tf for the z-coordinate.

Maybe you want to include the change in the git hub version of the driver.

**Comment by mani-monaj** [comment]
Good catch. I set it to be fixed in the next release.
