### ISSUE TITLE
wall clock time or simulated clock time of the timestamps of IMU[questions]

### ISSUE THREAD

**Issue by Brianyg** [AutonomyLab/ardrone_autonomy#158]
Hi, I am wondering since the ROS uses computer's system clock as a time source, the time stamp of the IMU and camera are wall clock time or simulated clock time? How could I get the simulated clock time? Thanks:)

**Comment by mani-monaj** [comment]
They are both set using `ros::Time` API therefore they are set to the wall time or simulated clock time transparently by ROS. Quoting from [ROS Time & Duration Docs](http://wiki.ros.org/roscpp/Overview/Time):

> ROS has the ability to setup a simulated Clock for nodes. Instead of using platform time routines, you should use roscpp's time routines for accessing the current time, which will work seamlessly with simulated Clock time as well as wall-clock time.
