### ISSUE TITLE
Tag 28 is an unknown navdata option tag

### ISSUE THREAD

**Issue by raultron** [AutonomyLab/ardrone_autonomy#159]
Hi, 

Last month I bought a new Parrot Ar.Drone and I have been using the ardrone_autonomy package, I have no problems with the functionality of the package. However, since the first day that I tested this package every time that I launch the main node using this command:

rosrun ardrone_autonomy ardrone_driver

I receive a lot of  this messages in the terminal:

Tag 28 is an unknown navdata option tag
Tag 29 is an unknown navdata option tag

Any idea what can be happening?.

**Comment by mani-monaj** [comment]
Parrot updated the firmware of AR-Drones without updating the message definitions in the SDK. Therefore some new Navdata payloads are not recognized by the [released] SDK.
