### ISSUE TITLE
AR Drone Parameters - travelling_enable, travelling_mode

### ISSUE THREAD

**Issue by guicn32** [AutonomyLab/ardrone_autonomy#162]
Do these parms have any usage? I was not able to find descriptions either in ardrone_autonomy nor in the Ardrone Developer Guide. Thanks!

**Comment by mani-monaj** [comment]
Unfortunately those params are not described in the official developer guide. You may consider asking this question on Parrot's new [Developer Forum](http://forum.developer.parrot.com/). Please feel free to update the documentation if you find any useful information.
