### ISSUE TITLE
Image topic and Camera_info unsynchronized

### ISSUE THREAD

**Issue by jbosch** [AutonomyLab/ardrone_autonomy#17]
Hi all,

The messages of the Image and Camera info are not synchronized and that can cause problems to people working with that images...
My suggestion is this little modification in ardrone_driver.cpp (line 452):

```
    sensor_msgs::Image image_msg;        
    sensor_msgs::Image::_data_type::iterator _it;

    // Image and info msg need the same time stamp.
    ros::Time camera_time = ros::Time::now();

    image_msg.header.stamp = camera_time;
    cinfo_msg_hori.header.stamp = camera_time;
    cinfo_msg_vert.header.stamp = camera_time;

    if (cam_state == ZAP_CHANNEL_HORI)
```

Thank you,

Josep Bosch
Ocean System Lab
Heriot-Watt University

**Comment by mani-monaj** [comment]
Thank you for the patch, however this issue has been mentioned in #13 and #14. Necessary changes (similar to your patch) to fix that has been committed in acc441ec9844567cc5e139f6e02a55d35f5a33eb .

Are you using the latest code?

**Comment by jbosch** [comment]
You are totally right. After a git pull the modifications where there.

thanks!

**Comment by mani-monaj** [comment]
You are welcome.
