### ISSUE TITLE
Control Inputs

### ISSUE THREAD

**Issue by Sriherams** [AutonomyLab/ardrone_autonomy#171]
Hi,
Can we able to change our control inputs from linear and angular velocities to actual control inputs provided by the AR Drone SDK 2.0 Developers guide? 
Since we are having some singularities while controlling the drone, is there a way to change the command velocity (linear & angular) to the inputs given below?
phi : Left/right angle 
theta : Front/back angle 
gaz : Vertical speed 
yaw : Angular speed

Thank You in advance...

**Comment by mani-monaj** [comment]
Inputs are actually interpreted in the same way as you described. 

linear.x and linear.y control pitch and roll (angles) 
linear.z and angular.y control gaz and yaw (speed)

The conversion is done by the SDK/Drone by multiplying these values to corresponding `*max*` [parameter](http://ardrone-autonomy.readthedocs.org/en/latest/parameters.html). For example `linear.x` is multiplied by `euler_angle_max` by the drone which results in a `linear.x * euler_angle_max` pitch.

**Comment by Sriherams** [comment]
What about angular.x and angular.y?

**Comment by mani-monaj** [comment]
Those degrees of freedom are not directly controllable, thus those inputs
are ignored.

**Comment by Sriherams** [comment]
Thank You.

So in this repository the command velocity linear.x is directly linked to 'ardrone_at_set_progress_cmd' in the SDK - (i.e.) AT*PCMD = %d,%d,%d,%d,%d,%d (refer : AR Drone SDK Developer Guide)

Am I right?

**Comment by mani-monaj** [comment]
Yes.
