### ISSUE TITLE
Getting input data

### ISSUE THREAD

**Issue by pulver22** [AutonomyLab/ardrone_autonomy#177]
Hi all,

I am working with the ardrone 2 for a project. I need to get the voltage/current used as input data to the controller/motors but I don't know where to look at. Is there a topic to subscribe or a service to call?

Thank you for your help!

**Comment by mani-monaj** [comment]
Please check "Selective Navdata" section of the documentation:

http://ardrone-autonomy.readthedocs.org/en/latest/reading.html#selective-navdata-advanced

[`navdata_pwm`](https://github.com/AutonomyLab/ardrone_autonomy/blob/indigo-devel/msg/navdata_pwm.msg) might be what you are looking for.
