### ISSUE TITLE
Flat Trim

### ISSUE THREAD

**Issue by devagl** [AutonomyLab/ardrone_autonomy#18]
I noticed that doing a flat trim before every take-off sometimes drastically improves the accuracy of the sonar data(as it is now calibrated to zero) and leads to more stable take-offs...Unfortunately I don't have the time now to figure out how pull requests work, so please consider adding this code to enable flat trims!

in `ardrone_driver.cpp` add

``` c
flatTrim_sub = node_handle.subscribe("ardrone/flatTrim",1,&flatTrimCallback);
```

in `ardrone_driver.h` add

``` c
ros::Subscriber flatTrim_sub;

in `teleop_twist.cpp` add

void flatTrimCallback(const std_msgs::Empty &msg)
{
    vp_os_mutex_lock(&twist_lock);
    ROS_INFO("Setting flat trim now!");
    ardrone_at_set_flat_trim();
    ROS_INFO("Flat trim Set!");
    vp_os_mutex_unlock(&twist_lock);
}
```

user then publishes empty message to 'ardrone/flatTrim' topic to do a  flat trim!

**Comment by mmyself** [comment]
sounds good to me.

**Comment by mani-monaj** [comment]
Thanks for the code @devmax . 

My previous attempts to use flat-trim was not successful. Once I put a `printf` in the actual function in `ARDroneLib` to see if it catches and executes flat-trim. I noticed that the `printf` seemed to get executed when the program exits. I did not go further, so I want to ask if you are completely sure that the command gets executed and has an effect?

**Comment by devagl** [comment]
Hi Mani,

I didn't actually do the printf test like you, but what I did was to do a flat trim while echo-ing the navdata from the drone. In the landed state the altitude is automatically zero, but the rotXYZ values seem to be reset everytime I gave the command. More concretely, I did a flat trim a couple of times while the drone was in the air, and it crashed as expected..So there is something definitely going on!

The other ARDrone tool commands (set_ui_pad and set_Progressive_cmd) seem to work fine, so I see no reason why this shouldn't!

**Comment by mani-monaj** [comment]
> I didn't actually do the printf test like you, but what I did was to do a flat trim while echo-ing the navdata from the drone. In the landed state the altitude is automatically zero, but the rotXYZ values seem to be reset everytime I gave the command. More concretely, I did a flat trim a couple of times while the drone was in the air, and it crashed as expected..So there is something definitely going on!

That's the correct way to testing of course.

**Comment by devagl** [comment]
@mani-monaj did you put the printf commands in ardrone_at_mutex.c? I did that and they didn't get executed..however even when i put the print commands in ardrone_at_set_ui_pad_value, they didn't get executed, although of course the drone takes off and lands just fine..any idea what the problem could be? I'm not very well versed with mutexes!

**Comment by mani-monaj** [comment]
@devmax I think the whole idea of putting `printf` in `ARDroneLib`'s low level functions is wrong and misleading. However I have no explanation about the reason :pensive:

**Comment by devagl** [comment]
@mani-monaj I agree...but you said that's the correct way of testing it...what did you mean then?

**Comment by mani-monaj** [comment]
I meant the method that you used which tested the functionality rather than execution. Sorry for being vague.

**Comment by devagl** [comment]
oh I see, in that case do you want to commit the changes?

**Comment by mani-monaj** [comment]
> oh I see, in that case do you want to commit the changes?

Sure. As soon as I can.

**Comment by mani-monaj** [comment]
Thanks for the contribution. 

Note: `flattrim` has been implemented as a service.
