### ISSUE TITLE
setflightanimation service

### ISSUE THREAD

**Issue by rohithagaram** [AutonomyLab/ardrone_autonomy#199]
ardrone flight animation services are not working
ERROR: Service [/ardrone/setflightanimation] is not available.

**Comment by mani-monaj** [comment]
What is the output of `rosservice list`?

**Comment by rohithagaram** [comment]
[k.txt](https://github.com/AutonomyLab/ardrone_autonomy/files/682531/k.txt)
![ser11](https://cloud.githubusercontent.com/assets/22973154/21612919/03e40956-d1f9-11e6-8964-93625dd869d4.jpg)
please find the above attachments

**Comment by rohithagaram** [comment]
please some one help me with this issue

**Comment by mani-monaj** [comment]
@rohithagaram Are you running the AR-Drone simulation via `tum_simulator` package? I don't think that the Gazebo simulation of AR-Drone implements any flight animation.
