### ISSUE TITLE
ARDrone Cam-url

### ISSUE THREAD

**Issue by devagl** [AutonomyLab/ardrone_autonomy#20]
So I'm using the April Tag Detector for the autonomous landing operation, and that requires me to specify a url of the camera I want it to stream the images from. For example, the URL of my webcam is 

v4l2:///dev/video0

Is there a way I can specify the url of the drone's bottom camera to the application?

**Comment by mani-monaj** [comment]
Unfortunately I am not aware of any methods to do so. I think a better place to ask this question is on http://asnwers.ros.org

BTW, I found this ROS package quite robust and easy to use for tag detection: [ar_track_alvar](http://www.ros.org/wiki/ar_track_alvar)

**Comment by devagl** [comment]
Thanks for the link Mani, it does seem to be a great option. I have it installed and built on my computer, but I keep facing this error everytime I try to run it with rviz:

#25 0xad45365b in operator() (
    a0=<error reading variable: access outside bounds of object referenced via synthetic point

(similar to http://answers.ros.org/question/43745/pcl-filter-nodelet-crashes/)

did you have a similar problem? its been driving me crazy..so any help would be amazing...

**Comment by mani-monaj** [comment]
@devmax I haven't had such a problem. Unfortunately, I have no idea how to fix it :confused:

**Comment by devagl** [comment]
Thanks anyways Mani..
