### ISSUE TITLE
ardrone_autonomy

### ISSUE THREAD

**Issue by ajayfuloria** [AutonomyLab/ardrone_autonomy#203]
Hi!!

I am from Computer Vision lab, Indian Institute of Technology Madras. We are working on a project which deals with autonomous indoor path planning of quadcopters. Our platform is TX 1 (Nvdia Tegra) and we are using ROS kinetic for our project. 

Presently, ardrone_autonomy is not supported for kinetic. I request if you can publish the same for kinetic.

Thanks and regards.

**Comment by mani-monaj** [comment]
@ajayfuloria 

This driver is available for ROS *Kinetic* as binary for `x86_64` and `i386`. Nvidia Tegra TX1 is an `arm` platform. You need to compile the driver from source on this target.  The discussion in the following topic might be helpful to you (although might not be directly applicable): https://github.com/AutonomyLab/ardrone_autonomy/issues/71
