### ISSUE TITLE
Can I use ardrone_autonomy if I have ros kinetic?

### ISSUE THREAD

**Issue by Maunsi** [AutonomyLab/ardrone_autonomy#209]
I'm a beginner in ROS so I don't know if this is impossible or not

**Comment by pulver22** [comment]
You can, just download ros-kinetic-ardrone-autonomy!

**Comment by Maunsi** [comment]
Thanks!

**Comment by szubair100** [comment]
did you do a git clone command?
`git clone -b ros-kinetic-ardrone-autonomy https://github.com/AutonomyLab/ardrone_autonomy.git`

I am still new to ros
