### ISSUE TITLE
catkin_make ardrone_autonomy fail

### ISSUE THREAD

**Issue by jianan1995** [AutonomyLab/ardrone_autonomy#213]
I am using ubuntu 16.04 and Ros kinetic on odroid xu4 and i encounter some problems
reference site: https://github.com/krishnan793/ar2landing_neural
Anyone can help me!

odroid@odroid:~$ cd catkin_ws/
odroid@odroid:~/catkin_ws$ catkin_make
Base path: /home/odroid/catkin_ws
Source space: /home/odroid/catkin_ws/src
Build space: /home/odroid/catkin_ws/build
Devel space: /home/odroid/catkin_ws/devel
Install space: /home/odroid/catkin_ws/install
####
####
####
####
[ 93%] Built target std_msgs_generate_messages_cpp
[ 93%] Built target geometry_msgs_generate_messages_cpp
[ 93%] Built target _ardrone_autonomy_generate_messages_check_deps_LedAnim
[ 93%] Built target _ardrone_autonomy_generate_messages_check_deps_navdata_vision_raw
[ 93%] Built target _ardrone_autonomy_generate_messages_check_deps_navdata_adc_data_frame
[ 93%] Built target _ardrone_autonomy_generate_messages_check_deps_navdata_vision
[ 93%] Built target _ardrone_autonomy_generate_messages_check_deps_navdata_wifi
[ 93%] Built target _ardrone_autonomy_generate_messages_check_deps_navdata_video_stream
[ 93%] Built target _ardrone_autonomy_generate_messages_check_deps_navdata_watchdog
[ 93%] Built target _ardrone_autonomy_generate_messages_check_deps_navdata_vision_detect
[ 93%] Built target _ardrone_autonomy_generate_messages_check_deps_navdata_hdvideo_stream
[ 93%] Built target _ardrone_autonomy_generate_messages_check_deps_navdata_time
[ 93%] Built target _ardrone_autonomy_generate_messages_check_deps_navdata_altitude
[ 93%] Built target _ardrone_autonomy_generate_messages_check_deps_RecordEnable
[ 93%] Built target _ardrone_autonomy_generate_messages_check_deps_navdata_pwm
[ 93%] Built target _ardrone_autonomy_generate_messages_check_deps_navdata_trims
[ 93%] Built target _ardrone_autonomy_generate_messages_check_deps_navdata_trackers_send
[ 93%] Built target _ardrone_autonomy_generate_messages_check_deps_navdata_kalman_pressure
[ 93%] Built target _ardrone_autonomy_generate_messages_check_deps_vector31
[ 93%] Built target _ardrone_autonomy_generate_messages_check_deps_Navdata
[ 93%] Built target _ardrone_autonomy_generate_messages_check_deps_navdata_rc_references
[ 93%] Built target _ardrone_autonomy_generate_messages_check_deps_navdata_euler_angles
[ 93%] Built target _ardrone_autonomy_generate_messages_check_deps_navdata_magneto
[ 93%] Built target _ardrone_autonomy_generate_messages_check_deps_navdata_gyros_offsets
[ 93%] Built target _ardrone_autonomy_generate_messages_check_deps_navdata_vision_of
[ 93%] Built target _ardrone_autonomy_generate_messages_check_deps_navdata_demo
[ 93%] Built target _ardrone_autonomy_generate_messages_check_deps_navdata_zimmu_3000
[ 93%] Built target _ardrone_autonomy_generate_messages_check_deps_navdata_phys_measures
[ 93%] Built target _ardrone_autonomy_generate_messages_check_deps_navdata_games
[ 93%] Built target _ardrone_autonomy_generate_messages_check_deps_CamSelect
[ 93%] Built target _ardrone_autonomy_generate_messages_check_deps_matrix33
[ 93%] Built target _ardrone_autonomy_generate_messages_check_deps_navdata_pressure_raw
[ 93%] Built target _ardrone_autonomy_generate_messages_check_deps_vector21
[ 93%] Built target _ardrone_autonomy_generate_messages_check_deps_FlightAnim
[ 93%] Built target _ardrone_autonomy_generate_messages_check_deps_navdata_wind_speed
[ 93%] Built target _ardrone_autonomy_generate_messages_check_deps_navdata_vision_perf
[ 93%] Built target geometry_msgs_generate_messages_nodejs
[ 93%] Performing update step for 'ardronelib'
[ 93%] Built target geometry_msgs_generate_messages_eus
[ 93%] Built target std_msgs_generate_messages_nodejs
[ 93%] Built target std_msgs_generate_messages_eus
[ 93%] Built target std_msgs_generate_messages_py
[ 93%] Built target geometry_msgs_generate_messages_py
[ 93%] Built target _ardrone_autonomy_generate_messages_check_deps_navdata_raw_measures
[ 93%] Built target std_msgs_generate_messages_lisp
[ 93%] Performing configure step for 'ardronelib'
[ 93%] Built target geometry_msgs_generate_messages_lisp
No configure
[ 93%] Built target _ardrone_autonomy_generate_messages_check_deps_navdata_references
[ 93%] Performing build step for 'ardronelib'
make[3]: warning: jobserver unavailable: using -j1.  Add '+' to parent make rule.
[ 93%] Built target ardrone_autonomy_generate_messages_cpp
[ 93%] Built target ardrone_autonomy_generate_messages_lisp
[ 93%] Built target ardrone_autonomy_generate_messages_eus
[ 93%] Built target ardrone_autonomy_generate_messages_nodejs
[ 93%] Built target ardrone_autonomy_generate_messages_py
[ 93%] Built target ardrone_autonomy_gencpp
Libs already extracted
Building target static
[ 93%] Built target ardrone_autonomy_generate_messages
Architecture armv7l is already built
Creating universal static lib file from architectures armv7l
Build done.
Building ARDroneTool/Lib
cc video_mem32.c
/tmp/ccurfkwM.s: Assembler messages:
/tmp/ccurfkwM.s:74: Error: bad instruction `bswap r3'
generic.makefile:231: recipe for target '../../Soft/Build/targets_versions/vlib_PROD_MODE_Linux_4.9.27-35_GNU_Linux_usrlibccachegcc_5.4.0/video_mem32.o' failed
make[8]: *** [../../Soft/Build/targets_versions/vlib_PROD_MODE_Linux_4.9.27-35_GNU_Linux_usrlibccachegcc_5.4.0/video_mem32.o] Error 1
vlib.makefile:104: recipe for target 'all' failed
make[7]: *** [all] Error 2
Makefile:167: recipe for target 'build_vlib' failed
make[6]: *** [build_vlib] Error 2
Makefile:170: recipe for target 'all' failed
make[5]: *** [all] Error 2
Makefile:84: recipe for target 'build_libs' failed
make[4]: *** [build_libs] Error 2
Makefile:20: recipe for target 'all' failed
make[3]: *** [all] Error 2
ardrone_autonomy/CMakeFiles/ardronelib.dir/build.make:110: recipe for target '/home/odroid/catkin_ws/devel/src/ardronelib-stamp/ardronelib-build' failed
make[2]: *** [/home/odroid/catkin_ws/devel/src/ardronelib-stamp/ardronelib-build] Error 2
CMakeFiles/Makefile2:532: recipe for target 'ardrone_autonomy/CMakeFiles/ardronelib.dir/all' failed
make[1]: *** [ardrone_autonomy/CMakeFiles/ardronelib.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2
Invoking "make -j8 -l8" failed

**Comment by Garrr123** [comment]
Hello, did u solve this problem?
