### ISSUE TITLE
Detection of shell tags with front camera?

### ISSUE THREAD

**Issue by mikehamer** [AutonomyLab/ardrone_autonomy#22]
Hi Guys,

Firstly I want to thank you for releasing this driver publicly, it's been a huge assistance to me.

I've been trying the last few days to enable shell-tag detection from the front camera of my AR.Drone 2.0, but unfortunately without success. The following parameters are set to the drone:

SET ~bitrate_ctrl_mode         : 0.00
SET ~max_bitrate               : 4000.00
SET ~outdoor                   : 1.00
SET ~flight_without_shell      : 1.00
SET ~altitude_max              : 5000.00
SET ~altitude_min              : 100.00
SET ~enemy_colors              : 3.00
SET ~enemy_without_shell       : 0.00
SET ~control_vz_max            : 2000.00
SET ~control_yaw               : 350.00
SET ~euler_angle_max           : 0.50
SET ~bitrate                   : 4000.00
SET ~navdata_demo              : 0.00
SET ~detect_type               : 10.00
SET ~detections_select_h       : 32.00
SET ~detections_select_v_hsync : 128.00

Where:
enemy_colors = 3 = ARDRONE_DETECTION_COLOR_ORANGE_BLUE (my tag color)
detect_type = 10 = CAD_TYPE_MULTIPLE_DETECTION_MODE
detections_select_h = 32 = TAG_TYPE_SHELL_TAG_V2
detections_select_v_hsync = 128 = TAG_TYPE_BLACK_ROUNDEL

Detection of the black roundel from the bottom camera works successfully and reliably.

Do you have any suggestions about what I could be doing wrong?

Thanks and best regards,
Mike

**Comment by mani-monaj** [comment]
Cause & Discussion in Topic: #24
