### ISSUE TITLE
ardrone/flattrim does not seem to exist

### ISSUE THREAD

**Issue by jrhizor** [AutonomyLab/ardrone_autonomy#23]
In the documentation, it says to call the service ardrone/flattrim. After running the driver successfully, the service does not exist, and after searching the directories I couldn't find it. Has it been implemented yet?

**Comment by mani-monaj** [comment]
The `flattrim` service added to the driver in 6bab013d70bd286187da5651a21772476cf08630 , are you using the latest code?
