### ISSUE TITLE
Ability to hover without enabling the "hover" state

### ISSUE THREAD

**Issue by parcon** [AutonomyLab/ardrone_autonomy#28]
The hover state takes into account features on the image plane to keep the ardrone stationary, but  I would like to be able to hover without using the cv methods. So far I believe that using very small velocities in the cmd_vel/linear message is the best way to accomplish this. 

According to the SDK this is a simple bit value that is sent with the command velocity. Is their a way to set this bit manually? Maybe the cmd_vel/angular/x or cmd_vel/angular/y could be high-jacked for this function, since they are not in use.

**Comment by mani-monaj** [comment]
> According to the SDK this is a simple bit value that is sent with the command velocity. Is their a way to set this bit manually? Maybe the cmd_vel/angular/x or cmd_vel/angular/y could be high-jacked for this function, since they are not in use.

This is already implemented I guess. If you look at [this line](https://github.com/AutonomyLab/ardrone_autonomy/blob/master/src/teleop_twist.cpp#L150), sending very small values for all velocities (0 will also work), will _set_ the hover bit in the command velocity.

**Comment by parcon** [comment]
My intention is to hover without the imaging control loop. The only way I can see to do that is to modify that line of code so that I can switch the mode independent of the inputs. I hope I'm making my point clear- I want to send zero command inputs while not engaging the hover state. The discontinuous hover state makes the dynamics much more complex to model.

**Comment by mani-monaj** [comment]
In order for me to understand it better: You need to send zero velocities to Drone without the _hover_ bit being set automatically?

**Comment by parcon** [comment]
Yes. The ability to turn on or off the hover state (state 3) independently of the control inputs.

Thanks again for all the work on this project.

**Comment by mani-monaj** [comment]
Thanks to @mikehamer, this issue has already been addressed in his proposed changes. I hope the feature will find its way to `dev-unstable` soon.

**Comment by mani-monaj** [comment]
Discussions and pull request in #31.
