### ISSUE TITLE
Not able to lift the ardrone more than 50 cm?? Suggestions

### ISSUE THREAD

**Issue by kkboss33** [AutonomyLab/ardrone_autonomy#29]
I0m starting to use ROS and this library, and I made this simple program to lift the ardrone more than a certain threshold (threshold = umbral in my program). First I send and empty message and to /ardrone/takeoff , it take offs, and the when I start running my program, the ar drone looses altitude and it is not able to reach an altitude greater than 40 cm or so. I'll really appreciate tips or advices... I'm new at this stuff... 

Some defines and variables are not used, i declared them thinking in using them afterwards
# include "ros/ros.h"
# include "ardrone_autonomy/Navdata.h"
# include "geometry_msgs/Twist.h"
# include cstdio
# include cstdlib
# define ROTX_REF 0.15
# define ROTY_REF 8.2
# define ROTX_UMBRAL 20
# define ROTY_UMBRAL 20

float altitud;
float rotx;
float roty;
float rotz;

float umbral = 400;
float vz=0;
float ax=0;
float ay=0;
bool flag = true;

void navDataCallback(const ardrone_autonomy::Navdata::ConstPtr& navigationData){
  if (flag){
    umbral_rotz = navigationData->rotZ;
    umbral = navigationData->altd + umbral;
    flag = false;
  }
  altitud = navigationData->altd;
  ROS_INFO("%f \t %f \t error: %f", altitud, umbral, umbral-altitud);
}

int main(int argc, char *\* argv){
  ros::init(argc, argv, "ardrone");
  ros::NodeHandle n;
  ros::Subscriber navDataSub = n.subscribe("/ardrone/navdata", 100, &navDataCallback);

  ros::Publisher pub = n.advertise <geometry_msgs::Twist> ("/cmd_vel",1000);

  ros::Rate loop_rate(10);

  while(ros::ok){
    geometry_msgs::Twist msg;
    if (altitud>umbral+200){
      vz = -1.0;
    }
    else if (altitud<umbral){
      vz = 1.0;
    }
    else{
      vz = 0;
    }

```
msg.linear.z = vz;
pub.publish(msg);
ros::spinOnce();
loop_rate.sleep();
```

  }
  return 0;
}

**Comment by mikehamer** [comment]
Nothing jumps out at me as being wrong with your code (but obviously something is because it's not working). What does your ROS_INFO output say?

**Comment by kkboss33** [comment]
In the code I showed, it prints the altitude it normally varies from 0 to 600, umbral (threshold) its only the altitude or height taken as a reference for the ardrone to reach it, but it never does... its always sending +1 for linear.z but it just hovers.... 

I also tested the drone_telop package from the ardrone 1.0 library, and i'm able to telop it, but same happens, it cant never lift beyond 50 cm....

i dont know if maybe is something with the initial parameters for the ardrone, beacause when i sent /ardrone/takeoff it lifts pretty much, around 1meter. but then when it changes to flying mode it looses height, never able to lift more again..

thanks for the help

**Comment by mikehamer** [comment]
Assuming you're using the latest version of ardrone_autonomy, try putting the following lines into your launch file:

<pre>
&lt;node name="ardrone_driver" pkg="ardrone_autonomy" type="ardrone_driver" output="screen"&gt;
.... (other parameters)
&lt;param name="altitude_max" value="5000" /&gt;
&lt;param name="altitude_min" value="300" /&gt;
.... (other parameters)
&lt;/node&gt;</pre>

Although the default `altitude_max` should be much more than 50cm... (3m if I remember correctly)

**Comment by kkboss33** [comment]
ok i'll do it, i guess you mean the ardrone_autonomy in the dev-unstable branch... do i have to install or delete the other package ardrone_autonomy???

**Comment by mikehamer** [comment]
Correct, for this to have any effect you will need to be running the dev-unstable branch, these fixes haven't yet made their way to the master branch.

**Comment by kkboss33** [comment]
ok thanks, that fixed the issue I started playing with the parameters in the launch file... i think the most critical factors were altitude min which i set to 1000 (1m) and the vertical velocity (2000 mm/s), and then it work fine

thank youi very much for your help

**Comment by mani-monaj** [comment]
Happy to hear that :)
