### ISSUE TITLE
no video after pulling the new changes

### ISSUE THREAD

**Issue by mmyself** [AutonomyLab/ardrone_autonomy#3]
Hi, i am not sure why and if it is really in issue.
But after pulling the new updates i have no video more.
any ideas what can go wrong there.
is it possible the no video subscriber thing make the trouble for me?
i only check if the video is there with 
rosrun image_view image_view image:=/ardrone/image_raw

with a reset to  
git reset 58d20cdbded4d017aea1d

it works again.

greets jan

**Comment by mani-monaj** [comment]
Thanks for reporting this. There was a bug in number of subscribers check in `publish_video`. It has been fixed in ef81277061353ed72a1c80b32cf28ace17c4dbea . Have you tried the latest commit?

**Comment by mmyself** [comment]
yes i testet it with commit ef81277, and there is no video with:
rosrun image_view image_view image:=/ardrone/image_raw

anything what i can check and tell you?

**Comment by mani-monaj** [comment]
Thanks for testing. It should be fixed in the latest commit: 909ee16d96d4fab024a042bb136098070c49e54a

**Comment by mmyself** [comment]
back on the computer, sorry for the late response. 
now everything works well.
this can be closed.

**Comment by mani-monaj** [comment]
Thanks.
