### ISSUE TITLE
Unable to run ardrone_driver on drone 1.0 (firmware 1.7.11)

### ISSUE THREAD

**Issue by gatmeh** [AutonomyLab/ardrone_autonomy#32]
Hello,

I am working with both the ardrone 1.0 and 2.0. When I run the ardrone_driver while connected to the  drone 2.0 it runs fine. However, when I run the driver while connected to the drone 1.0 I get a message that it connected successfully with a 0%  battery and then looses the nave data. The LED lights then turn red. This is all despite the fact that my battery was fully charged. 

Below is what I see in my terminal:

Timeout when reading navdatas – resending a navdata request on port 5554
Timeout when reading navdatas – resending a navdata request on port 5554
Timeout when reading navdatas – resending a navdata request on port 5554
[INFO] [1353539677.060302095]: Successfully connected to 'My ARDrone' (AR-Drone 1.0 – Firmware: 1.7.11) – Battery(%): 0
Timeout when reading navdatas – resending a navdata request on port 5554

**Comment by mikehamer** [comment]
Hmm, this is strange, I have had the driver working on my v1.0 before. I will test it again tomorrow and see what happens.

Are you using the master branch or the dev-unstable?

**Comment by gatmeh** [comment]
I am not too proficient with code development lingo, but I would assume I have the master branch which I got from 
$ git clone https://github.com/AutonomyLab/ardrone_autonomy.git

**Comment by mani-monaj** [comment]
The `master` branch has changed in last 15 minutes. No need to check the `dev-unstable` now. Just do a `git pull` & `rosmake --pre-clean`

**Comment by mikehamer** [comment]
As Mani suggested, try running the following:

$ roscd ardrone_autonomy
$ git pull
$ rosmake --pre-clean

This will fetch the latest changes from the `master` branch, where we have implemented a new startup/configuration process.

Also, try running the driver using the launch file. It will load some custom parameters from the launch file and then set them on the drone. This shouldn't really affect the startup sequence, but I would be interested to hear the result nonetheless.

$ roslaunch ardrone_autonomy ardrone.launch

It's 1AM here. When I get into uni tomorrow I'll try the driver out on my AR.Drone 1.0 and let you know the result. Good luck!

**Comment by parcon** [comment]
I would suggest updating the code on the ardrone via iPhone or other method. Maybe the firmware is out of date.  I just ran some testing using an ARdrone 1.0 with no problems :
$ rosun ardrone_autonomy ardrone_driver

**Comment by gatmeh** [comment]
Can you please tell me what firmware version you have on your drone?

**Comment by parcon** [comment]
Here is the output of my ardrone_driver:

[ INFO] [1353542040.607544616]: Successfully connected to 'My ARDrone' (AR-Drone 1.0 - Firmware: 1.11.5) - Battery(%): 100

**Comment by mani-monaj** [comment]
I also guess 1.7 firmware is too old. Try updating the firmware.

**Comment by gatmeh** [comment]
I updated the firmware and everything runs great now. Thank you all for contributing.

**Comment by mani-monaj** [comment]
Good to hear that :)
