### ISSUE TITLE
Failure rosmake ardrone_autonomy with ROS Groovy 

### ISSUE THREAD

**Issue by overbit** [AutonomyLab/ardrone_autonomy#35]
I installed new release of ROS (Groovy) and when I compile ardrone_autonomy rosmake returned an 
error. I resolve by changing ardrone_driver.cpp like below:

// IMU - Rotation Matrix
    btQuaternion q;
    q.setEulerZYX(msg.rotZ \* _DEG2RAD, msg.rotY \* _DEG2RAD, msg.rotX \* _DEG2RAD);
    tf::quaternionTFToMsg(q, imu_msg.orientation);

---->
 // IMU - Rotation Matrix
    tf::Quaternion q;
    q.setEulerZYX(msg.rotZ \* _DEG2RAD, msg.rotY \* _DEG2RAD, msg.rotX \* _DEG2RAD);
    tf::quaternionTFToMsg(q, imu_msg.orientation);

**Comment by mani-monaj** [comment]
Thank you very much for reporting this. I need to check if all `bt*` stuff needs to be changed or not.
