### ISSUE TITLE
Commanding multiple drones

### ISSUE THREAD

**Issue by parcon** [AutonomyLab/ardrone_autonomy#46]
The tread has seemed a little dead lately....so how about another question- I've been having trouble getting multiple drones working with the drivers. Has anyone found a good method for multiple drones? I'm expecting to use multiple wireless cards, and if necessary, some custom static routes.

**Comment by mani-monaj** [comment]
I could successfully control multiple drones with the driver. It needs some basic hacking on the drone. I will put up the information on the wiki early next week.

**Comment by parcon** [comment]
Could you please post that information? I'm having trouble implementing what little advice I have found so far concerning flying multiple drones from one machine.

**Comment by mani-monaj** [comment]
Sorry for the delay. Here is the [first draft](https://github.com/AutonomyLab/ardrone_autonomy/wiki/Multiple-AR-Drones).

**Comment by parcon** [comment]
Thanks again.
