### ISSUE TITLE
Patch for ROS Groovy ardrone_driver

### ISSUE THREAD

**Issue by warp1337** [AutonomyLab/ardrone_autonomy#47]
I just tried ti build the ardrone_driver in ROS Groovy. In Groovy some things concerning the bullet engine have been changed[1]. That's why the driver won't build (btQuaternion not defined). Here's my proposed patch:

--- ardrone_driver.cpp  2012-12-21 15:17:32.706078979 +0100
+++ ardrone_driver.cpp.old      2012-12-21 15:27:34.022090067 +0100
@@ -2,7 +2,6 @@
 #include "teleop_twist.h"
 #include "video.h"
 #include <signal.h>
-#include <tf/LinearMath/Quaternion.h>

 ////////////////////////////////////////////////////////////////////////////////
 // class ARDroneDriver
@@ -699,7 +698,7 @@
     imu_msg.linear_acceleration.z = msg.az \* 9.8;

```
 // IMU - Rotation Matrix
```
-    tf::Quaternion q;
-    btQuaternion q;
   q.setEulerZYX(msg.rotZ \* _DEG2RAD, msg.rotY \* _DEG2RAD, msg.rotX \* _DEG2RAD);
   tf::quaternionTFToMsg(q, imu_msg.orientation);

[1] http://ros.org/wiki/bullet/ChangeList

**Comment by mani-monaj** [comment]
Thanks for reporting this. This issue has been already reported and fixed in `dev-unstable` branch. It will be soon merged into `master`.
