### ISSUE TITLE
Question about cmd_vel

### ISSUE THREAD

**Issue by sytang** [AutonomyLab/ardrone_autonomy#48]
Hi,

I was wondering how the cmd_vel commands are relayed to the AR.Drone. When a linear-x is specified, is there an internal controller in the node that translates the desired linear-x to a pitch command to send to the drone? Or is setting linear-x the same as giving the drone a desired pitch (ie. is the command ardrone_at_set_progress_cmd(0, 0, 0.5, 0, 0) sent to the drone, or something of that nature?)? If there is some internal controller present, is there a way to directly send desired pitch and roll angles to the drone? Thank you!

Sarah

**Comment by mikehamer** [comment]
Hi Sarah,

There is no internal velocity controller present, rather the cmd_vel message was hijacked for use in this driver (I'm not sure why, the decision was made before my time).

Setting linear.x=1 will send a pitch=1 command to the drone. Likewise a linear.y=1 will send roll=1, linear.z=1 will send z-velocity=1, and angular.z=1 will set yaw-velocity=1.

What angle is commanded by a pitch=1 command (for example) can be adjusted by configuring the parameters in the launch file.

Hope this helps,
Mike

**Comment by sytang** [comment]
That definitely helps - thank you for such a quick response! 

Sarah
