### ISSUE TITLE
Import ardrone_autonomy.msg

### ISSUE THREAD

**Issue by ephreim-labs** [AutonomyLab/ardrone_autonomy#49]
I have problems when trying to import "from ardrone_autonomy.msg import NavData" with python.
Could you help me?

**Comment by mikehamer** [comment]
Firstly, it should be: `from ardrone_autonomy.msg import Navdata` (lowercase d)

Secondly, make sure you have: `import roslib; roslib.load_manifest('my_project_name')` at the beginning of the python file, this will load the manifest and then add the dependency paths to your python path so you can import their messages, etc.

Thirdly, make sure you have ardrone_autonomy defined as a dependency in your manifest file: `<depend package="ardrone_autonomy" />`

I have a fully working python example here: https://github.com/mikehamer/ardrone_tutorials_getting_started

Let me know if that helps and if you have any further questions.

Cheers,
Mike
