### ISSUE TITLE
Fuerte rosdep

### ISSUE THREAD

**Issue by savoyark** [AutonomyLab/ardrone_autonomy#5]
Hi,

I'm pretty new with ROS so please, bear with me. 
When I entered

rosdep install ardrone_autonomy

into the terminal, I got

ERROR: the following packages/stacks could not have their rosdep keys resolved to system dependencies:
ardrone_autonomy: Cannot locate rosdep definition for [libsdl-dev]

I'm currently using Ubuntu 12.04 with ROS Fuerte. I checked to make sure libsdl-dev was installed on my OS, and it said it has libsdl1.2-dev. I also tried changing the manifest.xml file in ardrone_autonomy to say libsdl1.2-dev instead of libsdl-dev, but that didn't help.

Can I please get some help on this issue? Thanks!

EDIT: 
I've already looked at

http://answers.ros.org/question/35426/problem-with-linking-sdl-when-compiling-ardrone_brown-node/

They had the same problem, but the version of ardrone_autonomy I'm using already has SDL at the end of the target_link_libraries(...).

**Comment by mani-monaj** [comment]
Thanks for reporting this. ROS Fuerte has a [new way](http://www.ros.org/wiki/release/Releasing/fuerte) for handling rosdep dependencies. I don't think you need to run `rosdep` at all. Run `build_sdk.sh` and then `rosmake ardrone_autonomy` as stated in `README`.
