### ISSUE TITLE
Latching on takeoff/land/reset topics

### ISSUE THREAD

**Issue by dmillard** [AutonomyLab/ardrone_autonomy#50]
I'm using roscpp, and can't seem to get the drone to take off unless I enable latching on the takeoff publisher:

``` cpp
ros::Publisher launch = n.advertise<std_msgs::Empty>("ardrone/takeoff", 5, true);
ros::Duration(1.0).sleep();
std_msgs::Empty empty;
launch.publish(empty);
```

Even then (and with or without latching on the land publisher) I can't get the drone to land from roscpp.

However, command line works great for takeoff landing and reset:

``` bash
$ rostopic pub -1 /ardrone/takeoff std_msgs/Empty
```

Why?

**Comment by mani-monaj** [comment]
That's odd. Is that all your code? Is there any particular reason that you are not using a ROS loop?

**Comment by dmillard** [comment]
Here's the main method:

``` cpp
ros::init(argc, argv, <nodename>);
ros::NodeHandle n;
ros::Rate loop_rate(10);
ros::Duration(1.0).sleep();

ros::Publisher launch = n.advertise<std_msgs::Empty>("ardrone/takeoff", 5);
ros::Publisher land = n.advertise<std_msgs::Empty>("ardrone/land", 5);
ros::Publisher reset = n.advertise<std_msgs::Empty>("ardrone/reset", 5);
ros::Publisher twist = n.advertise<geometry_msgs::Twist>("cmd_vel", 10);
ros::ServiceClient camchannel = n.serviceClient<ardrone_autonomy::CamSelect("ardrone/setcamchannel");

if(ros::ok()) {
    ardrone_autonomy::CamSelect camsrv;
    camsrv.request.channel = 1;
    camchannel.call(camsrv)
    launch.publish(at.empty_msg)
}

while(ros::ok()) {
    ros::spinOnce()
    loop_rate.sleep()
}
```

There's also a subscriber and a callback happening that I've left out: the problem existed before and after the subscriber was added.  However, I have noticed that the seemingly extraneous `ros::Duration(1.0).sleep()` statement is actually in the wrong place: it's meant to be after the initialization of the publishers, etc.  This was adapted from code with the sleep statement in the "correct" place, that did not have this problem.

I'll check when I have access to the drone and report back tomorrow.

**Comment by parcon** [comment]
Where do you define the empty message? Also, I've found that sending the message for a small period of time gets past that problem. Example code [here](https://github.com/parcon/arl_ardrone_examples/blob/master/src/takeoff.cpp). Although you can use a much shorter time period as you see fit or watch the state of the robot to know when you can stop sending the takeoff message (much better)

**Comment by dmillard** [comment]
Moving the sleep statement to in between the publisher initialization and the first message did the trick for me.  However, I'll rewrite to check the state of the drone: that seems much more reliable.

Thanks for the help.

**Comment by walk1ndude** [comment]
Also we can use getNumSubscribers() method, like this:

int main(int argc, char **argv) {
...
ros::Publisher takeoff_topic = nh.advertise<std_msgs::Empty>("ardrone/takeoff");
while (takeoff_topic.getNumSubscribers() == 0) {
      sleep(1); //sleep a bit
}
takeoff_topic.publish(std_msgs::Empty()); //now we're ready to go

**Comment by ziggBee30** [comment]
I am getting following error : 

 ‘Empty’ is not a member of ‘std_msgs’
  ros::Publisher launch = nh.advertise<std_msgs::Empty>("/ardrone/takeoff", 5);


any help please !

**Comment by xiaoshan-lin** [comment]
You should include #include <std_msgs/Empty.h> in your header file
