### ISSUE TITLE
Turn on recording onto USB drive?

### ISSUE THREAD

**Issue by sameerparekh** [AutonomyLab/ardrone_autonomy#52]
Does the ardrone_driver expose the interface to turn on and off video recording to the USB drive? I noticed the video_on_usb parameter, which defaults to 1, but I connected a USB drive to my AR.Drone and recording did not happen. I also quickly reviewed the AR.Drone SDK documentation and source code, and I couldn't find a call in there which enabled recording to the USB. Any ideas?

Thanks
-s

**Comment by mani-monaj** [comment]
I have not looked into it myself Sameer, but it is something that I will need in near future. I do not have time during next two weeks to do that, but any helps would be really appreciated.

**Comment by sameerparekh** [comment]
So I experimented by adding a service toggleusbrecord which calls the macro ARDRONE_TOOL_CONFIGURATION_ADDEVENT to set the video_on_usb parameter, but as far as I could tell (by telnetting in and looking in the /data/video/usb1 directory) it didn't start recording. I also experimented with the bits which send the ros parameters over -- I removed the bit which says if(param != default) so it would send all parameters, even the ones set to default (video_on_usb defaults to 1, so the parameter wasn't getting sent).. that also didn't turn on recording.

Perhaps there is another parameter that needs to be turned on or changed in order to enable the recording to USB.

I did make sure that my Android app was able to turn on recording, that works. I may snoop the TCP connection between my android and the ar.drone, that may help me see if anything else also needs to be set.

**Comment by mani-monaj** [comment]
Thanks for looking into that @sameerparekh. When this driver was being developed, there were no good official  example of video proccesing available using SDK. However [there is one now](https://projects.ardrone.org/boards/1/topics/show/5022), that might help.

**Comment by sameerparekh** [comment]
Unfortunately I think that video code only deals with the wifi stream, not the USB recording -- at least that's what it looks like. I grep'd through the code and saw no mention of USB.

**Comment by sameerparekh** [comment]
Pull request #53
