### ISSUE TITLE
camera toggle doesn't work

### ISSUE THREAD

**Issue by zweistein** [AutonomyLab/ardrone_autonomy#54]
Hey!

I'm using an AR-Drone 2.0 with Firmware: 2.2.6. I try to switch between the bottom and front cam with $ rosservice call /ardrone/togglecam. But the result is that the /ardrone/front video feed is passed to the /ardrone/bottom so when i toggle the front video cam feed in on both topics and not different camera feeds on different topics.

I tired to launch the driver with the ardroen.launch, my.launch and with rosrun. Same result. The heli is on the ground, it works only after take off?
Am I missing  something/ doing wrong, or this is a **bug**?
![Screenshot](https://f.cloud.github.com/assets/3353356/89922/5ca2d15c-655c-11e2-82d5-7653e27e00af.png)

**Comment by ubuntuslave** [comment]
I can say that I faced the same problem with both of my AR Drones (v1.0 and
v2.0), so I stopped there. I heard it works for some other people, but
unfortunately not for me.

Carlos

**Comment by zweistein** [comment]
Is there any method to change the feed? I need the bottom feed for displacement tracking and image process.
Elod

**Comment by mani-monaj** [comment]
That's interesting! Could you please tell me you Drone's firmware number?

**Comment by mani-monaj** [comment]
One more thing. Does the camera toggle works when using iPhone app?

**Comment by ubuntuslave** [comment]
I remember it didn't work through the iPhone app either. I haven't flown the drone in a few months since then.

Carlos

**Comment by zweistein** [comment]
I previously my tutor tired with a smart phone(android OS) and the camera toggle worked, I'm using an AR-Drone 2.0 with Firmware: 2.2.6. Is this firmware outdated or toggle is not supported?

**Comment by zweistein** [comment]
Any updates on this camera issue?

**Comment by krisdestruction** [comment]
I'm getting this issue with ROS Groovy. What ROS versions are you guys using?

**Comment by krisdestruction** [comment]
Also I am on the firmware 2.3.3. I'm considering upgrading to the 2.4.8 firmware.

**Comment by mani-monaj** [comment]
I will double check the camera toggle using the latest firmware (2.4.x). The older versions might have some problems with camera toggle.

**Comment by krisdestruction** [comment]
I restarted the whole system and restarted the drone. That seemed to fix the problem for me a few times.

**Comment by thanh-pham** [comment]
Does anyone get this toggle to work? I'd be nice if both camera feed can be streamed at the same time without toggling

**Comment by NRS-ks** [comment]
I am also having the same issue. I can toggle the cams easily with the iPhone app. However, the camera does not change using "rosservice call /ardrone/togglecam". I am using the latest version of the code and I do get the messages saying "Setting camera channel to : 1" or "Setting camera channel to : 0". 
I also tried changing the parameter "video_channel" so as to change the default camera view to 1, however it does not have any effect either.
Any help in this regards will be greatly appreciated.

**Comment by mani-monaj** [comment]
I will investigate the bug in camera toggle as soon as possible. Thank you for the report.

Streaming both cameras at the same time is not supported by the SDK though.

**Comment by mani-monaj** [comment]
@NRS-ks The camera toggle works for me on ROS _Hydro_ and AR-Drone 1 (firmware 1.1.15) with driver version 1.33. The _Fuerte_ branch has been End-Of-Lifed. It is using an older version of the SDK. That might be the root cause of the issue. I strongly recommend that you consider upgrading to _Hydro_ since _Groovy_ is going to be EOL soon.

**Comment by sayadyaghoobi** [comment]
i'm working with python module. i set the bottom camera for setting, but it gives me the different images sometimes from front camera, other time from bottom camera. but i don't know what is wrong with it. i tried **drone.setConfig("video:video_channel","1")** but nothing happens. if anyone has solved this problem please let me know.
