### ISSUE TITLE
slower takeoff

### ISSUE THREAD

**Issue by ashlih** [AutonomyLab/ardrone_autonomy#55]
Hi all,

i am ashlih, i am newbie with ardrone and still learning.

i was wondering, is there a way to takeoff but with more slower speed,
so i can adjust the height of the first takeoff?

thank you very much for your answer..

**Comment by mpoli** [comment]
As far as I know, the take off procedure is a high-level command that is executed by the Parrot Program.elf controller directly inside the drone processor. If this is really the case (pending confirmation) it is unlikely that a change will be possible in this driver. You may check github.com/ardrone/ardrone and try to find it there to make sure.

Hope this helps.

**Comment by ashlih** [comment]
Thank you MPoli for your answer..
