### ISSUE TITLE
Problem with navdata_pwm.altitude_integral

### ISSUE THREAD

**Issue by damanfb** [AutonomyLab/ardrone_autonomy#58]
While flying an ardrone parrot 2.0, we are seeing a random drop in altitude. Watching the values from navdata_pwm, we noticed that the altitude_integral is resetting from 60.0 to 0.0 when the drop occurs. The integral term then rebuilds and the quad rises back to the desired altitude.

Has anyone else seen issues with this value resetting and if so how it can be fixed?

**Comment by parcon** [comment]
I'm interested in this problem as well. Has anyone else seen it or found a remedy?

**Comment by mani-monaj** [comment]
I will close this issue to inactivity. If you have any new details, please update and re-open it.
