### ISSUE TITLE
Groovy supported driver, but catkin?

### ISSUE THREAD

**Issue by zweistein** [AutonomyLab/ardrone_autonomy#59]
I recently installed the Ros Groovy and i'm having difficulties with the installation of the driver package. As mentioned, since JAn 9. groovy is supported, what does that mean?

I cant find the package.xml and nor the CMakeList.txt is in the new format, so I'm not able to compile with catkin_make the package. 
The error is:

CMake Error at /opt/ros/groovy/share/catkin/cmake/catkinConfig.cmake:71 (find_package):
  Could not find a configuration file for package camera_info_manager.

  Set camera_info_manager_DIR to the directory containing a CMake
  configuration file for camera_info_manager.  The file will have one of the
  following names:

```
camera_info_managerConfig.cmake
camera_info_manager-config.cmake
```

Call Stack (most recent call first):
  ardrone_autonomy2/CMakeLists.txt:13 (find_package)

My package.xml downladable from: https://dl.dropbox.com/u/921645/package.xml

and the CMakeList.txt:

```
cmake_minimum_required(VERSION 2.4.6)
project(ardrone_autonomy)
include($ENV{ROS_ROOT}/core/rosbuild/rosbuild.cmake)    
find_package(catkin REQUIRED COMPONENTS roscpp rospy std_msgs message_generation image_transport sensor_msgs std_srvs tf camera_info_manager)    
catkin_package()    
include_directories(include  ${catkin_INCLUDE_DIRS} )    
#set the default path for built executables to the "bin" directory
set(EXECUTABLE_OUTPUT_PATH ${PROJECT_SOURCE_DIR}/bin)
#set the default path for built libraries to the "lib" directory
set(LIBRARY_OUTPUT_PATH ${PROJECT_SOURCE_DIR}/lib)    
#add_message_files()
#generate_messages()     
find_package(Boost REQUIRED )                           
set(SDK ARDroneLib/)
link_directories(${PROJECT_SOURCE_DIR}/lib/)
include_directories(${SDK} ${SDK}/FFMPEG/Includes ${SDK}/Soft/Common ${SDK}/Soft/Lib ${SDK}/VP_SDK     ${SDK}/VP_SDK/VP_Os/linux )
rosbuild_add_executable(ardrone_driver src/ardrone_driver.cpp src/video.cpp src/ardrone_sdk.cpp     src/teleop_twist.cpp)    
target_link_libraries(ardrone_driver pc_ardrone avcodec avutil swscale vlib  sdk SDL )
```

How can I install it? Where can i find a version which is for the new catkin maker?

**Comment by mani-monaj** [comment]
This issue have been fixed and merged into G/H/I branches.
