### ISSUE TITLE
Can not compile AR Drone SDK

### ISSUE THREAD

**Issue by Hendrik-Unger** [AutonomyLab/ardrone_autonomy#61]
Hi, I am trying to install your package in order to use the tum_ardrone package.
Unfortunately I can not build the AR Drone SDK:  After I issued the build command following error is displayed:

 Libs already extracted
Building target static
Architecture x86_64 is already built
Creating universal static lib file from architectures x86_64
Build done.
Checking required Ubuntu packages ...
ok.
Building ARDroneTool/Lib
ar rcs libvlib.a video_codec.o video_controller.o video_mem32.o video_dct.o video_huffman.o video_macroblock.o video_packetizer.o video_picture.o video_quantizer.o P263/p263_codec.o P263/p263_huffman.o P263/p263_mb_layer.o P263/p263_gob_layer.o P263/p263_picture_layer.o P264/p264_zigzag.o P264/p264_transform.o P264/p264_Qp.o P264/p264_intra_pred.o P264/p264_inter_mc.o P264/p264_merge.o P264/p264_codec.o P264/p264.o P264/p264_gob_layer.o P264/p264_mb_layer.o P264/p264_picture_layer.o P264/video_p264.o Stages/vlib_stage_decode.o Stages/vlib_stage_encode.o UVLC/uvlc_codec.o UVLC/uvlc.o UVLC/uvlc_gob_layer.o UVLC/uvlc_mb_layer.o UVLC/uvlc_picture_layer.o Platform/x86/video_utils.o Platform/x86/UVLC/uvlc_codec.o
make[5]: /home/hendrik/bin/ar: Kommando nicht gefunden
make[5]: **\* [../../Soft/Build/targets_versions/vlib_PROD_MODE_Linux_3.5.0-21-generic_GNU_Linux_homehendrikbingcc_/libvlib.a] Fehler 127
make[4]: **\* [all] Fehler 2
make[3]: **\* [build_vlib] Fehler 2
make[2]: **\* [all] Fehler 2
make[1]: **\* [build_libs] Fehler 2
make: **\* [all] Fehler 2

Could you please give some advice how to fix this?
I am not exactly a linux expert, so please forgive me if this error is trivial.
I am using ROS Groovy on an Ubuntu 12.10 machine.

**Comment by mmyself** [comment]
make[5]: /home/hendrik/bin/ar: Kommando nicht gefunden

das ist der haken, der checkt die pfade nicht. ist ein linux problem und nicht von der drone software.
PATH nicht richtig gesetzt. du musst ar aus der console direkt aufrufen können.

**Comment by Hendrik-Unger** [comment]
Danke für den Hinweis.  Habe jetzt herausgefunden das ar ein Archivtool ist.   Ich kann es direkt aus der Konsole aufrufen, die Fehlermeldung bleibt aber leider trotzdem bestehen.

**Comment by Hendrik-Unger** [comment]
Okay ich habe das Problem gelöst, ar lag bei mir unter in einem anderen Ordner. 
Habe einfach einen symbolischen Link von diesem Ordner in mein home/bin Verzeichnis erstellt.

Danke noch einmal für die Hilfe

**Comment by mmyself** [comment]
super, freut mich das ich helfen konnte.
