### ISSUE TITLE
Switch between camera streams as fast as possible?

### ISSUE THREAD

**Issue by jespestana** [AutonomyLab/ardrone_autonomy#65]
Hello everyone,

I would like to acquire images from both AR Drone cameras as fast as possible. To do so I have programmed a test code using ROS (using the ardrone_autonomy driver https://github.com/AutonomyLab/ardrone_autonomy , which in turn uses the AR Drone SDK). From what I have seen, a fair ammount of images can be received (around 10-20) when switching between cameras. The problem is that part of the images received from the frontal camera are in reality from the bottom camera; and the same happens the other way around. For instance when I visualize the video streams "ardrone/front/image_rect_color" and "ardrone/bottom/image_rect_color" on two separate "image_view" nodes; I will get images from both cameras on both "image_view" windows. Has anybody encountered the same problem before?

I am using the latest version of the SDK and the ardrone_autonomy software on Ubuntu 12.04 and an AR Drone 2.0.

Please note that there other users interested on this issue:
https://projects.ardrone.org/boards/1/topics/show/1609
https://projects.ardrone.org/issues/show/172

My question is if other people are facing the same problem, and whether this bug is a problem on the SDK or on the ardrone_autonomy node.
Thanks for your help,

jespestana

**Comment by mani-monaj** [comment]
I've never experienced it myself. Do you have any updates regarding this issue?

**Comment by jespestana** [comment]
In the end, I decided to continue working using only the frontal camera. From the posts that I found on the SDK website I thought that it was not possible to get images from both cameras at the same time. 

Otherwise, I have no updates on this issue. I am sorry!

**Comment by mani-monaj** [comment]
Thank you for your update.
