### ISSUE TITLE
Error : Register publisher failed to contact master

### ISSUE THREAD

**Issue by tonystark12** [AutonomyLab/ardrone_autonomy#66]
Hi. Am using ardrone_autonomy package and trying to run the executable ardrone_driver

however, it is not working even after connecting to the drone. am getting the following error.

[ERROR] [1371144822.249433366]: [registerPublisher] Failed to contact master at [localhost:11311].  Retrying...

Can you please tell me wat is rong? Is it connection issue? I wanted to try this package, but am stuck here. please help me.

**Comment by pathammer** [comment]
The executable requires a ROS master to be running. This requires ROS core be installed. Try using one of the launch files: roslaunch ardrone_autonomy ardrone.launch

**Comment by tonystark12** [comment]
Thanks. It worked. I tried running roscore separately and then use rosrun.
I was able to run roslaunch. But I needed rosrun for other purposes as
well. That's why. Thank you again.
