### ISSUE TITLE
Bad Navdata, followed by seg fault

### ISSUE THREAD

**Issue by ayrton04** [AutonomyLab/ardrone_autonomy#69]
Hi,

When I run the ardrone_driver node, I get this:

---

Wait authentification
Wait authentification
Wait authentification
===================+> 192.168.1.1
[0m[ INFO] [1374177922.819663975]: Root Frame is: 0[0m
[0m[ INFO] [1374177922.821190042]: ~cov/imu_la set to [0.1, 0, 0, 0, 0.1, 0, 0, 0, 0.1][0m
[0m[ INFO] [1374177922.822553219]: ~cov/imu_av set to [1, 0, 0, 0, 1, 0, 0, 0, 1][0m
[0m[ INFO] [1374177922.823944586]: ~cov/imu_or set to [1, 0, 0, 0, 1, 0, 0, 0, 100000][0m
Deleting Profile -cea48d22
Deleting Application -e182b69b
Input device Teleop added
Starting thread video_stage
Starting thread video_recorder
Video recorder thread initialisation
Starting thread update_ros
Thread `update_ros` started 
 Set IP_TOS ok
Starting thread navdata_update

video stage thread initialisation

Starting thread ardrone_control
Thread navdata_update in progress...
Video multisocket : init 2 sockets
Video multisocket : connecting socket 0 on port 5555 UDP
Video multisocket : connecting socket 1 on port 5555 TCP
PA : MEMORY SPACE ALLOWED : 40 MB
Start thread thread_academy_download 
Academy download stage resumed
Start thread thread_academy
Start thread thread_academy_upload
Academy download stage paused
Timeout when reading navdatas - resending a navdata request on port 5554
Tag 43150 is an unknown navdata option tag
One option (0) is not a valid option because its size is zero
[Navdata] Checksum failed : 0 (distant) / 37543 (local)
Tag 43150 is an unknown navdata option tag
One option (0) is not a valid option because its size is zero
[Navdata] Checksum failed : 0 (distant) / 37191 (local)
Tag 43150 is an unknown navdata option tag
One option (0) is not a valid option because its size is zero
[Navdata] Checksum failed : 0 (distant) / 37508 (local)
Tag 43150 is an unknown navdata option tag
One option (0) is not a valid option because its size is zero
[Navdata] Checksum failed : 0 (distant) / 37169 (local)
Tag 43150 is an unknown navdata option tag
One option (0) is not a valid option because its size is zero
[Navdata] Checksum failed : 0 (distant) / 36609 (local)
Tag 43150 is an unknown navdata option tag
One option (0) is not a valid option because its size is zero
[Navdata] Checksum failed : 0 (distant) / 37529 (local)
Tag 43150 is an unknown navdata option tag
One option (0) is not a valid option because its size is zero
[Navdata] Checksum failed : 0 (distant) / 38587 (local)
Tag 43150 is an unknown navdata option tag
One option (0) is not a valid option because its size is zero
[Navdata] Checksum failed : 0 (distant) / 37612 (local)
Tag 43150 is an unknown navdata option tag
One option (0) is not a valid option because its size is zero
[Navdata] Checksum failed : 0 (distant) / 37095 (local)
Tag 43150 is an unknown navdata option tag
One option (0) is not a valid option because its size is zero
[Navdata] Checksum failed : 0 (distant) / 37584 (local)
Tag 43150 is an unknown navdata option tag
One option (0) is not a valid option because its size is zero
[Navdata] Checksum failed : 0 (distant) / 36774 (local)
Tag 43150 is an unknown navdata option tag
One option (0) is not a valid option because its size is zero
[Navdata] Checksum failed : 0 (distant) / 36905 (local)
Tag 43150 is an unknown navdata option tag
One option (0) is not a valid option because its size is zero
[Navdata] Checksum failed : 0 (distant) / 37519 (local)
Tag 43150 is an unknown navdata option tag
One option (0) is not a valid option because its size is zero
[Navdata] Checksum failed : 0 (distant) / 37463 (local)
One option (0) is not a valid option because its size is zero
[Navdata] Checksum failed : 0 (distant) / 36882 (local)
Tag 43150 is an unknown navdata option tag
One option (0) is not a valid option because its size is zero
[Navdata] Checksum failed : 0 (distant) / 37158 (local)
Tag 43150 is an unknown navdata option tag
One option (0) is not a valid option because its size is zero
[Navdata] Checksum failed : 0 (distant) / 35778 (local)
Tag 43150 is an unknown navdata option tag
One option (0) is not a valid option because its size is zero
[Navdata] Checksum failed : 0 (distant) / 35597 (local)
Tag 43150 is an unknown navdata option tag
One option (0) is not a valid option because its size is zero
[Navdata] Checksum failed : 0 (distant) / 37206 (local)
Tag 43150 is an unknown navdata option tag
One option (0) is not a valid option because its size is zero
[Navdata] Checksum failed : 0 (distant) / 37065 (local)
Tag 43150 is an unknown navdata option tag
One option (0) is not a valid option because its size is zero
[Navdata] Checksum failed : 0 (distant) / 37439 (local)
Tag 43150 is an unknown navdata option tag
One option (0) is not a valid option because its size is zero
[Navdata] Checksum failed : 0 (distant) / 36952 (local)
Tag 43150 is an unknown navdata option tag
One option (0) is not a valid option because its size is zero
[Navdata] Checksum failed : 0 (distant) / 37284 (local)
Tag 43150 is an unknown navdata option tag
One option (0) is not a valid option because its size is zero
[Navdata] Checksum failed : 0 (distant) / 37369 (local)
Tag 43150 is an unknown navdata option tag
One option (0) is not a valid option because its size is zero
[Navdata] Checksum failed : 0 (distant) / 36410 (local)
Tag 43150 is an unknown navdata option tag
One option (0) is not a valid option because its size is zero
[Navdata] Checksum failed : 0 (distant) / 36484 (local)
Tag 43150 is an unknown navdata option tag
One option (0) is not a valid option because its size is zero
[Navdata] Checksum failed : 0 (distant) / 36645 (local)
Tag 43150 is an unknown navdata option tag
One option (0) is not a valid option because its size is zero
[Navdata] Checksum failed : 0 (distant) / 37245 (local)
Tag 43150 is an unknown navdata option tag
One option (0) is not a valid option because its size is zero
[Navdata] Checksum failed : 0 (distant) / 37889 (local)
[0m[ INFO] [1374177927.896990172]:   SEND: CAT_COMMON/outdoor = 1.000000 (DEFAULT = 0.000000)[0m
[0m[ INFO] [1374177927.897107739]:   SEND: CAT_COMMON/enemy_colors = 3.000000 (DEFAULT = 1.000000)[0m
[0m[ INFO] [1374177927.897165449]:   SEND: CAT_APPLI/navdata_options = 268435456.000000 (DEFAULT = 65537.000000)[0m
[0m[ INFO] [1374177927.897252100]:   SEND: CAT_USER/euler_angle_max = 0.210000 (DEFAULT = 0.209440)[0m
[0m[ INFO] [1374177927.897301038]:   SEND: CAT_USER/control_yaw = 1.750000 (DEFAULT = 1.745329)[0m
[0m[ INFO] [1374177927.897469113]:   SEND: CAT_SESSION/video_codec = 129.000000 (DEFAULT = 32.000000)[0m
[0m[ INFO] [1374177927.897556546]:   SEND: CAT_APPLI/bitrate = 4000.000000 (DEFAULT = 1000.000000)[0m
[0m[ INFO] [1374177927.897624505]:   SEND: CAT_SESSION/max_bitrate = 4000.000000 (DEFAULT = 1000.000000)[0m
[0m[ INFO] [1374177927.897680146]:   SEND: CAT_SESSION/detect_type = 10.000000 (DEFAULT = 3.000000)[0m
[0m[ INFO] [1374177927.897739531]:   SEND: CAT_SESSION/detections_select_h = 32.000000 (DEFAULT = 0.000000)[0m
[0m[ INFO] [1374177927.897795344]:   SEND: CAT_SESSION/detections_select_v_hsync = 128.000000 (DEFAULT = 0.000000)[0m
Tag 43150 is an unknown navdata option tag
One option (0) is not a valid option because its size is zero
[Navdata] Checksum failed : 0 (distant) / 37025 (local)
Tag 43150 is an unknown navdata option tag
One option (0) is not a valid option because its size is zero
[Navdata] Checksum failed : 0 (distant) / 37154 (local)
Tag 43150 is an unknown navdata option tag
One option (0) is not a valid option because its size is zero
[Navdata] Checksum failed : 0 (distant) / 37081 (local)
Tag 43150 is an unknown navdata option tag
One option (0) is not a valid option because its size is zero
## [Navdata] Checksum failed : 0 (distant) / 36058 (local)

The seg fault occurs because of line 135 in ardrone_driver.cpp:

ROS_INFO("Successfully connected to '%s' (AR-Drone %d.0 - Firmware: %s) - Battery(\%): %d",
                         ardrone_control_config.ardrone_name,
                         (IS_ARDRONE1) ? 1 : 2,
                         ardrone_control_config.num_version_soft,
                         shared_raw_navdata->navdata_demo.vbat_flying_percentage);

shared_raw_navdata is null, and so we get a seg fault.

I put some of my own debug statements in the parrot drone, and here's what I got:

---

[Navdata] Checksum failed : 0 (distant) / 37640 (local)
pointer is 11661008, tag is 0
pointer is 11661156, tag is 1
pointer is 11661164, tag is 2
pointer is 11661216, tag is 3
pointer is 11661262, tag is 4
pointer is 11661278, tag is 5
pointer is 11661290, tag is 6
pointer is 11661378, tag is 7
pointer is 11661394, tag is 8
pointer is 11661418, tag is 9
pointer is 11661510, tag is 10
pointer is 11661566, tag is 11
pointer is 11661582, tag is 12
pointer is 11661626, tag is 13
pointer is 11661718, tag is 14
pointer is 11661826, tag is 15
pointer is 11662190, tag is 16
pointer is 11662518, tag is 17
pointer is 11662526, tag is 18
pointer is 11662566, tag is 19
pointer is 11662631, tag is 20
pointer is 11662643, tag is 21
pointer is 11662661, tag is 22
pointer is 11662744, tag is 23
pointer is 11662808, tag is 24
pointer is 11662880, tag is 25
pointer is 11662912, tag is 26
pointer is 11662920, tag is 27
pointer is 11663400, tag is 43150
Tag 43150 is an unknown navdata option tag
pointer is 11701809, tag is 0
## One option (0) is not a valid option because its size is zero

I was just printing out the value of the pointer, along with the tag value.

Any ideas? It's a 2.0 drone with the absolute latest firmware (2.4.1). Thanks!

**Comment by mani-monaj** [comment]
Thank you for your detailed report. Have you tried the driver before on older versions of the firmware?

**Comment by ayrton04** [comment]
I haven't, no. Do you have a specific version of the firmware that you know works well for a 2.0 drone? Also, do you know if it's possible to flash it with an older firmware?

**Comment by mani-monaj** [comment]
It seems to be that the latest AR-Drone 2.0 firmware 2.4.1 is not compatible with the old SDK, thus is not compatible with this ROS driver at the moment [1]. The driver works well with 2.3.3 firmware. I don't know however how to downgrade the firmware on the drone. I will put some time to figure out the problem myself and see if I can fix it. The ultimate solution is that Parrot should release a new SDK which supports the new firmware.

[1] https://projects.ardrone.org/boards/1/topics/show/5763#

**Comment by warp1337** [comment]
I just tried to use the 2.0.1 SDK (just replaced the ARDroneLib content and did some minor hacking) ... it basically works :dancer: BUT, I could not fly reliably :( This need further work, just FYI

**Comment by mani-monaj** [comment]
@warp1337 that's interesting. Could you please be more specific about the minor hacks?

**Comment by warp1337** [comment]
Yes, I will try to document this. Anyway, I found out how to downgrade the drone firmware in the meantime. You will need to buy an app for that. It's called drone control HD (approx. 5 USD). Sadly, for iPad only AFAIK...(http://forum.parrot.com/ardrone/en/viewtopic.php?id=7439). I was able to downgrade my drone to 2.3.3 which works with the autonomy package.

**Comment by ayrton04** [comment]
Actually, you don't need to do that. The firmware is freely available (just search for version 2.3.3). Download the file, and then simply open up any FTP client, upload the file, and then restart the vehicle. Voila!

**Comment by mani-monaj** [comment]
Some [progress](https://github.com/AutonomyLab/ardrone_autonomy/pull/75#issuecomment-27149895): 

> Ok, I managed to fix crashes on 2.4.x firmware by updating the SDK to 2.0.1. I have not tested it completely 
> during flights, but at least it works both for 2.3.x and 2.4.x firmwares. I will patch the SDK further to support the
> new GPS messages. I will move on to working on `catkin` branch soon. 
> The code (8c46987febf895d091df91c97e1a76c26a65a3fe) is now on `dev-unstable` branch.

**Comment by mani-monaj** [comment]
Can anyone please test flight using the `dev-unstable` branch?

**Comment by ayrton04** [comment]
I can at some point, sure. Great news with getting it to work with the new firmware, and for your efforts to get the GPS data included! Thanks.

**Comment by mani-monaj** [comment]
@ayrton04 Thank you for testing. Current code can not de-serialize GPS data. I am working on it.

**Comment by mani-monaj** [comment]
Fixed in ecec423f04f05103c361badbc328525a4d4b5ef5
