### ISSUE TITLE
Bottom Camera Feed

### ISSUE THREAD

**Issue by devagl** [AutonomyLab/ardrone_autonomy#7]
I'm able to run the ardrone_drive properly and also control its movements using the cmd_vel topic. 

When I do either rosrun image_view image_view image:=/ardrone/image_raw or rosrun image_view image_view image:=/ardrone/front/image_raw I can get a 640X360 pixel image.

But once I do rosrun image_view image_view image:=/ardrone/bottom/image_raw, I only get a blank window with no data..Right clicking gives a prompt saying "no data"!

Please help! I've made sure my firewall is disable while trying this, and have tested the bottom camera to be okay using both the Free Flight app and the Linux_sdk_demo...

**Comment by mmyself** [comment]
you have at first to switch with the service to the bottom camera.

Services
Toggle AR-Drone's Camera

Calling ardrone/togglecam service with no parameters will change the active video camera stream.

look in the readme

**Comment by ubuntuslave** [comment]
I have the same problem. Even when toggling the service (as suggested in the documentation) the bottom camera's topics never seem to be published. I haven't looked in the source code, but there might be some bug. Have verified the camera toggle works for you? Are we doing something  wrong?

Carlos

**Comment by devagl** [comment]
I toggled the camera stream using the service, but still no stream from the bottom camera...only front camera gives a steady video stream...
Is this a bug?

**Comment by mani-monaj** [comment]
Are you using the latest version of the code? I can confirm that the bottom camera stream works after calling the service. 

``` bash
[ardrone driver running]
rosservice call /ardrone/togglecam 

Setting camera channel to : 1 (output from driver)

rosrun image_view image_view image:=/ardrone/bottom/image_raw
[or]
rosrun image_view image_view image:=/ardrone/image_raw
```

Do you receive the "Setting camera channel to : 1" from ardrone driver?

**Comment by devagl** [comment]
Thank you Mani, it works well now..not sure what I did wrong earlier with mmyself's comment...
Will it be possible at some point to receive a simultaneous stream (bottom image embedded in corner of front image) ?

**Comment by mani-monaj** [comment]
You are welcome.

> Will it be possible at some point to receive a simultaneous stream (bottom image embedded in corner of front image) ?

Drone 1 with firmware 1.X supports Picture in Picture mode, but in Drone 2.0 this mode is not supported anymore.

**Comment by NRS-ks** [comment]
I am also having the same issue. I can toggle the cams easily with the iPhone app. However, the camera does not change using "rosservice call /ardrone/togglecam". I am using the latest version of the code and I do get the messages saying "Setting camera channel to : 1" or "Setting camera channel to : 0". 
I also tried changing the parameter "video_channel" so as to change the default camera view to 1, however it does not have any effect either.
Any help in this regards will be greatly appreciated.
