### ISSUE TITLE
Timeout when reading Navdatas

### ISSUE THREAD

**Issue by tonystark12** [AutonomyLab/ardrone_autonomy#70]
Hello,

Thank you for the ardrone_autonomy package that helped me to run the drone effectively. Recently, I got a new HP - Pavilion g6-2313AX 64 bit laptop, installed windows 8 and ubuntu 12.04 in it. I wanted to control drone from this laptop and installed necessary software in ubuntu. The package ardrone_autonomy was successful without errors.

This Ardrone 2.0 am trying to control is also a brand new one, I got just yesterday from amazon.com. I do the following to control it using ardrone_driver

roscore
(new terminal)
roscd ardrone_autonomy
rosrun ardrone_autonomy ardrone_driver

This is where am facing the problem. Either of the following 4 occurs, but system hang is occuring in all cases
1. wait authentication
   wait authentication
   wait authentication
   ==================> 192.168.1.1
   (system hang)
2. (after passing through wait authentication and few lines of code)
   start thread thread academy upload
   Timeout when reading navdatas - resending a navdata request on port 5554
   Timeout when reading navdatas - resending a navdata request on port 5554
   Timeout when reading navdatas - resending a navdata request on port 5554
   (system hang)
3. (after passing through wait authentication and few lines of code)
   start thread thread academy upload
   Timeout when reading navdatas - resending a navdata request on port 5554
   Timeout when reading navdatas - resending a navdata request on port 5554
   Timeout when reading navdatas - resending a navdata request on port 5554
   (few statements with [INFO] followed by information of memory size etc.>
   (system hang)

4.(after passing through wait authentication and few lines of code)
    start thread thread academy upload
    Academy download stage paused
(system hang)

Please help me here. am facing a deadline and am not able to complete it smoothly. Am trying to operate the same from different laptop to check if the mistake is with mine. But if it anything else you can identify, please help me.

Thanks,
LN

**Comment by tonystark12** [comment]
I followed help from following.. still not helping. also am not sure if I did it correct. your help is much appreciated. Thanks.
http://pharos.ece.utexas.edu/wiki/index.php/How_to_use_ROS_to_Control_the_AR_Drone_Parrot
http://gauth.fr/2011/09/introduction-to-the-ar-drone-sdk/

**Comment by mikehamer** [comment]
Hi Tony,

Is your laptop disconnected from all other networks? Make sure it isn't plugged into any wired networks when you connect (via wifi) to the AR.Drone. The reason for this, is that if a second network is on the 19.168.1.\* IP range, there are often routing problems, which will cause some of the behavior that you describe.

Mike

**Comment by tonystark12** [comment]
Hello Mike,

Thanks a lot for your reply. As you have suggested, I tried it already. I
would like to post my results, for a better picture.

This is my ifconfig before connecting to wifi

eth0      Link encap:Ethernet  HWaddr d4:c9:ef:63:7d:97
          inet addr:192.168.1.2  Bcast:192.168.1.255  Mask:255.255.255.0
          inet6 addr: fe80::d6c9:efff:fe63:7d97/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:45431 errors:0 dropped:0 overruns:0 frame:0
          TX packets:42290 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:57151284 (57.1 MB)  TX bytes:4464988 (4.4 MB)

lo        Link encap:Local Loopback
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:16436  Metric:1
          RX packets:2927 errors:0 dropped:0 overruns:0 frame:0
          TX packets:2927 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0
          RX bytes:288631 (288.6 KB)  TX bytes:288631 (288.6 KB)

After connecting to wifi, this is my config

eth0      Link encap:Ethernet  HWaddr d4:c9:ef:63:7d:97
          UP BROADCAST MULTICAST  MTU:1500  Metric:1
          RX packets:5804 errors:0 dropped:0 overruns:0 frame:0
          TX packets:6552 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:4409199 (4.4 MB)  TX bytes:1116148 (1.1 MB)

lo        Link encap:Local Loopback
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:16436  Metric:1
          RX packets:707 errors:0 dropped:0 overruns:0 frame:0
          TX packets:707 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0
          RX bytes:90281 (90.2 KB)  TX bytes:90281 (90.2 KB)

ra0       Link encap:Ethernet  HWaddr 1c:3e:84:b3:ed:f1
          inet6 addr: fe80::1e3e:84ff:feb3:edf1/64 Scope:Link
          UP BROADCAST MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:14 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)
          Interrupt:16

I tried to switch off both separately and connect. It still did not work.
Can you please elaborate? I really need help. Hope am not disturbing you.

Thanks,
LN

**Comment by mani-monaj** [comment]
After connecting to the Drone's wifi, can you `telnet 192.168.1.1` from the terminal? You should be able to log-in to the drone if the connection to the drone is established and working. I also noticed that when not connected to the drone your Ethernet (LAN) IP address is in 192.168.1.x subnet which causes a conflict. You must unplug your ethernet cable or disable the connection before connecting to the drone.

**Comment by tonystark12** [comment]
Yes,

As you said, I have an option asking me to login. How can I proceed from
there? And while connecting to drone, I alwyas removed the Lan connected to
my system. It still shows the eth0, so I did the following before proceeding

sudo ifconfig eth0 down

It still was causing problems. Now I have connected the drone and this is
my result of iwconfig

iwconfig
ra0       Ralink STA  ESSID:"ardrone2_276980"  Nickname:"RT3290STA"
          Mode:Managed  Frequency=2.412 GHz  Access Point:
90:03:B7:38:CB:12
          Bit Rate=65 Mb/s
          RTS thr:off   Fragment thr:off
          Link Quality=100/100  Signal level:-47 dBm  Noise level:-65 dBm
          Rx invalid nwid:0  Rx invalid crypt:0  Rx invalid frag:0
          Tx excessive retries:0  Invalid misc:0   Missed beacon:0

eth0      no wireless extensions.

lo        no wireless extensions.

and telnet gave this,

telnet 192.168.1.1
Trying 192.168.1.1...
Connected to 192.168.1.1.
Escape character is '^]'.
BCM96338 ADSL Router
Login:

Does these info say anything? And thank you so much for replying. Please do
reply again, when you have time.
but asap

Thanks,
LN

**Comment by mani-monaj** [comment]
> telnet 192.168.1.1 
> Trying 192.168.1.1... 
> Connected to 192.168.1.1. 
> Escape character is '^]'. 
> **BCM96338 ADSL Router Login:**

Your PC is clearly not connected to the drone. That is connected to your ADSL router. Assuming that the LAN cable is unplugged, the PC is probably connected to the ADSL router via wifi.

**Comment by tonystark12** [comment]
I am sorry. I unplugged the LAN and I tried it again. This is what I got :

Trying 192.168.1.1...
Connected to 192.168.1.1.
Escape character is '^]'.

BusyBox v1.14.0 () built-in shell (ash)
Enter 'help' for a list of built-in commands.

# help

## Built-in commands:

```
    . : [ [[ alias bg break cd chdir continue echo eval exec exit
    export false fg hash help jobs kill let local pwd read readonly
    return set shift source test times trap true type ulimit umask
    unalias unset wait
```

My apologies for not being clear.

Thanks,
LN

**Comment by mani-monaj** [comment]
Now you are connected :) What is the firmware version of the AR-Drone? You can check it using your iPhone or Android app.

**Comment by tonystark12** [comment]
I donn't have the app. Have been using drone for research purposes. I will
download it if its necessary. Meanwhile, can I come to know about it
without the app? Thanks for your help. I feel I can resolve this by today
:).

Thanks,
LN

**Comment by mani-monaj** [comment]
> I donn't have the app. Have been using drone for research purposes. I will download it if its necessary. Meanwhile, can I come to know about it without the app? Thanks for your help. I feel I can resolve this by today :).

You are welcome. It is better to have it, not only for determining the firmware number, but also to test if it can control the drone.

**Comment by tonystark12** [comment]
Sure. But can you help me here? Or is it that we can't proceed now without
the firmware number? Sorry for the cross question :)

Thanks,
LN

**Comment by tonystark12** [comment]
Hello,

Luckily now, all of a sudden, it just worked. But when I try again, it
failed. Any idea how? The academy stage was crossed, and it got connected.
But now, the same issues are repeating. Some saying about Root frame 0,
etc. and the system hangs. Please help me here.

Thanks,
LN

**Comment by tonystark12** [comment]
Am being permanently halted at academy stage download paused! Please do
tell me what this means. As this is a part of the code, can you tell me
what it tries to access and why it fails?

Thanks,
LN

**Comment by tonystark12** [comment]
Am being permanently halted at academy stage download paused! Please do
tell me what this means. As this is a part of the code, can you tell me
what it tries to access and why it fails?

**Comment by tonystark12** [comment]
I have attached the information regarding my drone in this mail. It seemed
to work fine with the app. Can you please help me now?

Thanks,
LN
