### ISSUE TITLE
Academy Download Stage paused

### ISSUE THREAD

**Issue by tonystark12** [AutonomyLab/ardrone_autonomy#72]
I previously posed an issue regarding timeout while sending navdatas. Now my system seems to continuously hand with this line at the last of compilcation  : 

Academy Download stage paused.

Any help please. Its almost 2 weeks and I haven't done anything. The ardrone_driver in ardrone_autonomy always worked fine, but it is not happening here. your help is much appreciated.

After connecting to drone, my iwconfig : 

ra0       Ralink STA  ESSID:"ardrone2_276980"  Nickname:"RT3290STA"
          Mode:Managed  Frequency=2.412 GHz  Access Point: 90:03:B7:38:CB:12  
          Bit Rate=65 Mb/s  
          RTS thr:off   Fragment thr:off
          Link Quality=100/100  Signal level:-54 dBm  Noise level:-60 dBm
          Rx invalid nwid:0  Rx invalid crypt:0  Rx invalid frag:0
          Tx excessive retries:0  Invalid misc:0   Missed beacon:0

eth0      no wireless extensions.

lo        no wireless extensions.

telnet 192.168.1.1 gives the following : 

Trying 192.168.1.1...
Connected to 192.168.1.1.
Escape character is '^]'.

BusyBox v1.14.0 () built-in shell (ash)
Enter 'help' for a list of built-in commands.
# 

As epr earlier issue comments, people said am connected. Can anyone temme why am I still not able to get through? 

Luckily, I was able to get through once, and that happened after I restarted my drone many a times and my wifi, checking telnet everytime and then it got through. But otherwise, consistently it gets hanged with

Academy download stage paused.

Please help me.

**Comment by mani-monaj** [comment]
This is most likely a wireless connection issue. Any updates on this?

**Comment by tonystark12** [comment]
I resolved it. Just forgot the trouble shoot steps. Will let you know when
I run it again. Mostly it was by changing the system, or the version of
Linux I guess. Will keep you posted.

Thanks,
LN

**Comment by mani-monaj** [comment]
@tonystark12 Any updates on this? If yes, please feel free to re-open this issue.
