### ISSUE TITLE
magnetometer problem

### ISSUE THREAD

**Issue by harke** [AutonomyLab/ardrone_autonomy#73]
I have managed to run the ardrone_autonomy pkg with my Ardrone via joystick. But it is very difficult to control it the Ardrone. in the terminal i get this message 

[ WARN] [1374753610.356924518]: There is something wrong with the magnetometer readings (Magnitude is extremely small).

Do somebody know how to fix this? Could this be the reason of the control problem.
thx

**Comment by pavel-kirienko** [comment]
I get these messages all the time, but everything works okay.

> Could this be the reason of the control problem.

Unlikely.

**Comment by protobits** [comment]
I get these on AR.Drone 1. I guess this could be fixed since there's no magnetometer on this drone.

**Comment by x75** [comment]
During hydro testing, i also noticed the magnetometer issue which is known from paparazzi: http://lists.paparazziuav.org/Interesting-flight-with-ARDrone2-and-master-branch-td14499.html

basically the magnetometer gets stuck and stops updating values. tracing navdata it can be seen that magX,Y,Z remain constant.

**Comment by mani-monaj** [comment]
The frequency of error message regarding magnetometer being stuck has been decreased since version 1.3.4 of the driver. Please report the magnetometer stuck bug/issue to Parrot.
