### ISSUE TITLE
Calibrating the AR.Drone 2.0 camera

### ISSUE THREAD

**Issue by ghost** [AutonomyLab/ardrone_autonomy#78]
Hi everyone,

I am trying to calibrate the AR.Drone camera because it gives me double images and the images are quite transparent. 

I followed this tutorial: http://wiki.ros.org/camera_calibration/Tutorials/MonocularCalibration and my webcam could successfully detect my checkerboard. When I try it with the ardrone camera feed, it cannot detect the checkerboard. Does anyone know what I should do?

thank you!

**Comment by mani-monaj** [comment]
Any updates on this?
