### ISSUE TITLE
looking for a launchfile for starting with the ardrone and to say 'great job'

### ISSUE THREAD

**Issue by mmyself** [AutonomyLab/ardrone_autonomy#8]
hi mani-monaj , 
first off all i will say this. great work that you have done. 

it is for me the greatest, to look in the morning, if you have done something new.
the imu topic and also the camera calibration thing. all things that i want to do, but never had the time
or the experience to do this. fine to see how you solve all this things.
thx for all.

another question,
have you build launch files, where you use maybe things like robot_state_publisher or robot-pose-ekf
where i am able to see the drones doing in rviz. maybe like it was in the hector_quadrotor: packages.
or localize the drone via the tag detection?

this will be great if you publish something like that.

i build something like that with the starmac package, for the old drone. 
you can see here. 
git@github.com:mmyself/jh_ardrone.git
but this was yery rough.

all i really can recommend is the drone_teleop_3d i build,
great experience to fly the drone with a 3d mouse, because of the intuitive flying over the z-axis,

greats jan

**Comment by mani-monaj** [comment]
Thanks for your kind word Jan.

> have you build launch files, where you use maybe things like robot_state_publisher or robot-pose-ekf
> where i am able to see the drones doing in rviz. maybe like it was in the hector_quadrotor: packages.
> or localize the drone via the tag detection?

We have done some works on 3D localization of the drones. But the code is fairly unstable and unpolished. We may release the code when it comes out of development. 

> i build something like that with the starmac package, for the old drone.
> you can see here.
> git@github.com:mmyself/jh_ardrone.git
> but this was yery rough.

That really looks interesting. I should check it out.

> all i really can recommend is the drone_teleop_3d i build,
> great experience to fly the drone with a 3d mouse, because of the intuitive flying over the z-axis,

Maybe you can port/polish that code so we can include that in the ardrone_driver package alongside with a keyboard/joystick teleop?
